import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { init } from '../src/commands/init.js';
import {
  EXIT_INSTALL_FAILED,
  EXIT_OK,
  install,
} from '../src/commands/install.js';
import { checkPlatformStatus } from '../src/installers/platform-status.js';

describe('GitHub Copilot adapter', () => {
  let dir: string;

  beforeEach(async () => {
    dir = await mkdtemp(path.join(tmpdir(), 'mancode-copilot-'));
    await mkdir(path.join(dir, '.git'), { recursive: true });
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  it('installs copilot instructions and records copilot in config platforms', async () => {
    await silentInit(dir);

    const code = await install(dir, 'copilot');

    expect(code).toBe(EXIT_OK);
    const instructions = await readInstructions();
    expect(instructions).toContain('<!-- mancode:start -->');
    expect(instructions).toContain('# mancode for GitHub Copilot');
    expect(instructions).toContain('Platform adapter: GitHub Copilot');
    expect(instructions).toContain('mancode Prompt Conventions');
    expect(instructions).toContain('one bounded self-check');
    expect(instructions).toContain('bounded risk-based review');

    const config = JSON.parse(
      await readFile(path.join(dir, '.mancode', 'config.json'), 'utf-8'),
    );
    expect(config.platforms).toContain('claude-code');
    expect(config.platforms).toContain('copilot');
  });

  it('preserves user instructions and remains idempotent', async () => {
    await silentInit(dir);
    await mkdir(path.join(dir, '.github'), { recursive: true });
    await writeFile(
      path.join(dir, '.github', 'copilot-instructions.md'),
      '# User Instructions\n\nKeep this.\n',
      'utf-8',
    );

    await install(dir, 'copilot');
    await install(dir, 'copilot', { force: true });

    const instructions = await readInstructions();
    expect(instructions).toContain('# User Instructions\n\nKeep this.');
    expect(count(instructions, '<!-- mancode:start -->')).toBe(1);
    expect(count(instructions, '<!-- mancode:end -->')).toBe(1);
  });

  it('refreshes only the managed block on forced reinstall', async () => {
    await silentInit(dir);
    await install(dir, 'copilot');

    const instructionsPath = path.join(
      dir,
      '.github',
      'copilot-instructions.md',
    );
    const original = await readFile(instructionsPath, 'utf-8');
    await writeFile(
      instructionsPath,
      original.replace(
        'Platform adapter: GitHub Copilot',
        'Platform adapter: Old',
      ),
      'utf-8',
    );

    await install(dir, 'copilot', { force: true });

    const instructions = await readInstructions();
    expect(instructions).toContain('Platform adapter: GitHub Copilot');
    expect(instructions).not.toContain('Platform adapter: Old');
  });

  it('emits minimal content with --minimal', async () => {
    await silentInit(dir);

    await install(dir, 'copilot', { minimal: true });

    const instructions = await readInstructions();
    expect(instructions).toContain('mancode Practice Rules');
    expect(instructions).not.toContain('mancode Prompt Conventions');
  });

  it('does not create AGENTS.md for Copilot', async () => {
    await silentInit(dir);

    await install(dir, 'copilot');

    await expect(
      readFile(path.join(dir, 'AGENTS.md'), 'utf-8'),
    ).rejects.toThrow();
  });

  it('creates .github/prompts/ with 5 mode prompt files', async () => {
    await silentInit(dir);
    await install(dir, 'copilot');

    for (const mode of ['manba', 'man', 'manteam', 'manps', 'mansolo']) {
      const prompt = await readFile(
        path.join(dir, '.github', 'prompts', `${mode}.prompt.md`),
        'utf-8',
      );
      expect(prompt).toMatch(/^---\nagent: 'agent'\ndescription: /);
      expect(prompt).toContain('Mode Persistence');
      expect(prompt).toContain('YAGNI ladder');
    }
  });

  it('preserves a user-authored legacy man8 prompt during upgrade', async () => {
    await silentInit(dir);
    const promptsDir = path.join(dir, '.github', 'prompts');
    await mkdir(promptsDir, { recursive: true });
    const legacyPath = path.join(promptsDir, 'man8.prompt.md');
    await writeFile(legacyPath, '# user-authored man8 prompt\n', 'utf-8');

    await install(dir, 'copilot');

    await expect(readFile(legacyPath, 'utf-8')).resolves.toBe(
      '# user-authored man8 prompt\n',
    );
  });

  it('replaces a managed legacy mamba prompt with manba during upgrade', async () => {
    await silentInit(dir);
    const promptsDir = path.join(dir, '.github', 'prompts');
    const legacyPath = path.join(promptsDir, 'mamba.prompt.md');
    await mkdir(promptsDir, { recursive: true });
    await writeFile(
      legacyPath,
      '<!-- Managed by mancode:mode-file. Do not edit this file manually. -->\n# mancode mamba — Diagnosis\n',
      'utf-8',
    );

    await install(dir, 'copilot', { force: true });

    await expect(readFile(legacyPath, 'utf-8')).rejects.toThrow();
    await expect(
      readFile(path.join(promptsDir, 'manba.prompt.md'), 'utf-8'),
    ).resolves.toContain('# mancode manba');
  });

  it('preserves a user-authored legacy mamba prompt during upgrade', async () => {
    await silentInit(dir);
    const promptsDir = path.join(dir, '.github', 'prompts');
    const legacyPath = path.join(promptsDir, 'mamba.prompt.md');
    await mkdir(promptsDir, { recursive: true });
    await writeFile(legacyPath, '# user-authored mamba prompt\n', 'utf-8');

    await install(dir, 'copilot', { force: true });

    await expect(readFile(legacyPath, 'utf-8')).resolves.toBe(
      '# user-authored mamba prompt\n',
    );
  });

  it('keeps the managed legacy mamba prompt when manba cannot be written', async () => {
    await silentInit(dir);
    const promptsDir = path.join(dir, '.github', 'prompts');
    const legacyPath = path.join(promptsDir, 'mamba.prompt.md');
    await mkdir(promptsDir, { recursive: true });
    await writeFile(
      legacyPath,
      '<!-- Managed by mancode:mode-file. Do not edit this file manually. -->\n# mancode mamba — Diagnosis\n',
      'utf-8',
    );
    await mkdir(path.join(promptsDir, 'manba.prompt.md'));

    const code = await install(dir, 'copilot', { force: true });

    expect(code).toBe(EXIT_INSTALL_FAILED);
    await expect(readFile(legacyPath, 'utf-8')).resolves.toContain(
      '# mancode mamba',
    );
  });

  it('minimal force install removes existing prompts', async () => {
    await silentInit(dir);
    await install(dir, 'copilot');
    // Verify prompts exist before minimal
    await readFile(
      path.join(dir, '.github', 'prompts', 'manba.prompt.md'),
      'utf-8',
    );

    await install(dir, 'copilot', { force: true, minimal: true });

    await expect(
      readFile(
        path.join(dir, '.github', 'prompts', 'manba.prompt.md'),
        'utf-8',
      ),
    ).rejects.toThrow();
  });

  it('reports a minimal install ready even when user prompt files remain', async () => {
    await silentInit(dir);
    const promptsDir = path.join(dir, '.github', 'prompts');
    await mkdir(promptsDir, { recursive: true });
    await writeFile(
      path.join(promptsDir, 'custom.prompt.md'),
      '# custom prompt\n',
      'utf-8',
    );

    await install(dir, 'copilot', { minimal: true });
    const result = await checkPlatformStatus(dir, 'copilot', true);

    expect(result.ready).toBe(true);
    await expect(
      readFile(path.join(promptsDir, 'custom.prompt.md'), 'utf-8'),
    ).resolves.toBe('# custom prompt\n');
  });

  it('requires every generated prompt for a non-minimal install', async () => {
    await silentInit(dir);
    await install(dir, 'copilot');
    await rm(path.join(dir, '.github', 'prompts', 'manba.prompt.md'));

    const result = await checkPlatformStatus(dir, 'copilot', true);

    expect(result.ready).toBe(false);
    expect(result.detail).toContain('missing');
  });

  it('instructions include mansolo in prompt conventions', async () => {
    await silentInit(dir);
    await install(dir, 'copilot');

    const instructions = await readInstructions();
    expect(instructions).toContain('mansolo');
  });

  it('prompt files do not use $ or / prefix', async () => {
    await silentInit(dir);
    await install(dir, 'copilot');

    const manba = await readFile(
      path.join(dir, '.github', 'prompts', 'manba.prompt.md'),
      'utf-8',
    );
    expect(manba).not.toContain('$manba');
    expect(manba).not.toContain('/manba');
  });

  it('mansolo prompt maps state to solo not mansolo', async () => {
    await silentInit(dir);
    await install(dir, 'copilot');

    const mansolo = await readFile(
      path.join(dir, '.github', 'prompts', 'mansolo.prompt.md'),
      'utf-8',
    );
    expect(mansolo).toContain('"solo"');
    expect(mansolo).not.toContain('"mansolo"');
  });

  async function readInstructions(): Promise<string> {
    return readFile(
      path.join(dir, '.github', 'copilot-instructions.md'),
      'utf-8',
    );
  }
});

async function silentInit(dir: string): Promise<void> {
  const originalLog = console.log;
  const originalError = console.error;
  console.log = () => {};
  console.error = () => {};
  try {
    const code = await init(dir);
    if (code !== 0) {
      throw new Error(`silentInit failed: init exited with ${code}`);
    }
  } finally {
    console.log = originalLog;
    console.error = originalError;
  }
}

function count(value: string, needle: string): number {
  return value.split(needle).length - 1;
}
