/** Man orchestration only; shared review quality rules are injected separately. */
export const MAN_REVIEW_GUIDANCE: readonly string[] = [
  '- Use the shared review protocol on the existing Man TaskRef and its approved baseline. Collect the bounded inventory with `mancode review inspect --base <bound-baseHead> --json`; an inventory is input to review, not proof of semantic coverage. Keep file/behavior coverage, exclusions and gaps in the review report or existing supported evidence text, never add unsupported fields to the strict ledger.',
  '- Calling the manba review procedure does not create a diagnostic child, switch workflowMode, grant repair authority or replace the existing review/verification gates. Keep one module total review and targeted follow-up after concrete repairs. Use a child only for an actual isolated diagnosis under the existing parent snapshot and merge protocol; do not recreate stale children in a loop or treat their outcome as parent acceptance.',
  '- Match verification to risk: for a reproducible defect, first confirm the regression fails for the target behavior, make the smallest fix, then run that regression and affected checks; use test-first for suitable new automated behavior and controlled failure scenarios for locks, concurrency or recovery. Reuse passing behavior tests for refactors; documentation does not need an artificial Red. Environment, syntax or dependency failures are not a valid Red, weakening assertions is not a valid Green, and replay against an old revision does not prove historical test-first development. For verification policy 1 these remain workflow guidance; explicitly opted-in policy 2 tasks enforce their declared scenarios through captured Vitest evidence.',
  '- Identify the project checks from actual scripts and CI, then use their common entry point when available. For the mancode repository, `npm run check` runs the Quality checks against the newly built CLI; `npm run check:windows` prepares Windows lock checks, while the CI matrix still runs the real CMD, PowerShell and Git Bash smoke tests. A local pass never proves an unexecuted platform matrix. Preserve the original task policy, required surfaces, remaining checks and explicit governed Solo handoff commitments.',
  '- Enable execution gates only for a new local man delivery task when its execution policy is explicitly approved: add `--execution-policy <policy.json>` to workflow create man --delivery. Persist task-specific finite run/time/repair budgets, approved commands, TDD scenarios and local or remote_required delivery. Do not upgrade existing tasks or force TDD onto every kind of change. Independent manba diagnosis remains on its existing policy.',
  '- For verification policy 2 use `mancode workflow execution <TaskRef> inspect` to read the policy, budget and missing evidence. Execute approved checks with `run --file <input.json>` and declared tdd_red/tdd_green or regression_replay purposes; never submit automatic passed claims or whole-ledger apply. Delivery verify maps an exact approved command/surface/acceptance set to the same runner. Reserve each substantive repair through attempt-reserve before editing and settle it through attempt-finish with its real verification run IDs. The CLI does not intercept arbitrary host file edits.',
  '- Interrupted policy-2 runs retain their reservation. Use execution run-inspect, run-cancel or run-recover with the original runId; inspect/repair the existing operation when a journal needs repair. Never rerun an uncertain command automatically. A permanently missing receipt needs owner-approved run-reconcile after interruption: retain consumed allowance and report an exception, never a passing check. Budget exhaustion stops new execution but inspect, cancel, recover and explicit budget-extend/exception-decide/contract-revise remain available. Approval fields are audit declarations, not authenticated proof of a human decision. The final permitted successful attempt can complete; spent allowance alone is not a failure.',
  '- For remote_required policy-2 tasks, use execution ci-observe with the approved repository/workflow/job contract and exact candidate target. Each observation is a bounded read-only batch; pending or unavailable evidence needs explicit continuation within budget and never triggers a push or rerun. Unknown tested objects, including unsupported PR merge bindings, remain unverified. Remote completion makes one fresh charged observation outside task locks; reserve budget for it. Windows execution gates currently report capability unavailable before spawning, and POSIX cleanup covers the original process group only. Reuse the task and its counters across authorized reviewers and handoffs; unsupported cross-task budget transfer must not reset them.',
];
