/** Explicit review requests do not inherit diagnostic mutation authority. */
export const MANBA_REVIEW_GUIDANCE: readonly string[] = [
  '- First distinguish a diagnostic request from an explicit complete-review request. Ordinary manba diagnosis retains its existing reproduce, diagnose, fix, verify and typed-outcome protocol; invoking review never silently changes an existing diagnostic task.',
  '- For an independent review, establish the requested baseline, target and scope, then run `mancode review inspect --base <explicit-ref> --json` with the selected binary. Do not infer a PR base. This read-only inventory creates no actor, session or diagnostic TaskRef; a one-off review report is not Continuity authority and does not require diagnostic task creation or completion. This explicit review branch overrides diagnostic entry steps that would otherwise create identity, session or task state.',
  '- When review explicitly targets an existing Man TaskRef, use that task and its review context, actual workflowMode, policy, planDecision, approved scope and session permissions. Do not switch modes or create a child by default. A plan_only decision, completed task or read-only request grants no implementation or authority-write permission; report observations when applying evidence is not authorized.',
  '- The inventory compares the explicit base with HEAD, the index and the current working tree separately, including tracked tests, CI, deletions, renames and non-ignored untracked files. Check every indicated layer: a working-tree edit can hide different staged or committed content, and matching path/status does not mean matching content. Inventory exit 0 proves collection only, not semantic review, immutable content or passing checks. Missing Git, an invalid base, collection failure or unsupported/unverified contents remain visible gaps; rerun after changes and examine relevant ignored/generated/submodule contents explicitly when the contract requires them.',
  '- Independent review defaults to a report, not source repair. Run only applicable authorized checks; use the project check entry when available. The report states baseline/target, actual scope and exclusions, file and behavior coverage, findings with evidence, actual check results, environment gaps and next actions. Separate coverage complete, defects found and unverified behavior; never use fixed, verified, no_repro or manual_test_required to pretend that an audit report passed diagnostic completion.',
  '- For an authorized review of an existing Man task, record the result through its existing delivery review command or the corresponding old-policy review apply protocol, then read back the task state. Keep unsupported coverage details in the report/reference rather than adding fields to strict ledgers. A report or reviewer exit code is not evidence that the ledger was applied, and a completed report does not replace the task acceptance.',
  '- Reuse existing in-scope repair authorization when it applies; otherwise report findings without changing source. For a reproducible defect, confirm a test fails for the intended behavior before the minimal fix, then run the same behavior assertion and direct regression. Existing-code review cannot establish historical test-first development; label an old-version replay honestly. Preserve original diagnostic outcomes and child snapshot gates for a separately requested root-cause investigation.',
];
