/** Shared review procedure; these instructions do not add runtime gates. */
export const REVIEW_GUIDANCE: readonly string[] = [
  '- Establish an explicit review baseline and target before reviewing. For Git changes, run `mancode review inspect --base <approved-base-ref> --json` to inventory the baseline-to-HEAD changes and current working tree, including untracked files. Use the bound baseHead for a governed module; never guess a PR base from HEAD. Inspect is read-only inventory, not semantic review or applied acceptance evidence. If this command is unavailable on the selected binary, collect the equivalent Git inventory without switching binaries; missing Git or an unknown baseline remains an explicit coverage gap.',
  '- Account for every changed file and connect it to behavior and acceptance: implementation, callers, tests, CI, configuration, dependency locks, schemas, migrations, generated sources and contract documentation. Include deletions, renames and unchanged affected callers; review is not restricted to added lines. Group related files by behavior, retain a fallback for ungrouped files, and check contracts between groups. Record reviewed paths, outstanding paths, and exclusion reasons with alternative evidence; file assignment or a read marker alone does not prove semantic coverage.',
  '- Apply repository contracts and rules selected for language, file role and concrete risk. Read full relevant context and entry-to-result call paths instead of trusting an implementer summary. Check goal-to-code omissions, code-to-goal scope drift, failure/permission/concurrency/recovery boundaries and unjustified abstraction. Test, configuration and CI defects are reviewable defects too; verify that tests distinguish broken behavior from correct behavior and do not merely mirror implementation or mock away the acceptance boundary.',
  '- Keep every actionable required finding; do not cap findings at three or impose a finding quota. Use stable IDs, a triggering condition, contract basis, causal evidence and user impact; distinguish proven defects, required but unverified acceptance, and optional advice. Deduplicate the same root cause while preserving affected paths. Verify file/line anchors, including the old side for deletions. Retract a false positive with its evidence and reason; security or concurrency labels do not exempt a claim from fact checking.',
  '- Reuse applicable test and review evidence. Retain existing policy-required review domains and stages; do not add a second total review. Perform one total review, followed by targeted rechecks for concrete repairs or newly evidenced risks, not fixed repeated review rounds. Record unresolved coverage, unavailable tools and exhausted context/time budgets; an empty finding list or a successful reviewer process does not turn those gaps into a pass. A report must distinguish coverage completeness, unresolved findings, and unverified acceptance.',
  "- Derive required project checks from the actual project scripts and CI definitions, including install/lockfile, runtime versions, build-before-artifact tests, environment variables, operating systems and shell matrices. Prefer the project's shared check entry when present; do not assume every project uses npm or GitHub. In mancode itself, `npm run check` matches Quality checks and `npm run check:windows` supplies the Windows build/lock preparation; the three real Windows shell smoke runs remain separate. Run applicable checks once per unchanged subject/environment and keep original failures visible.",
  '- Local success and upstream publication do not prove remote CI success. When remote acceptance is required, identify the repository, candidate SHA, tested head/merge SHA, event, workflow, job/matrix and run attempt. Missing, skipped, neutral, stale, inaccessible or ambiguous required checks remain unverified unless the accepted contract explicitly makes them inapplicable. Do not reuse the latest green branch run or push merely to obtain a review result. This phase supplies review guidance, not a new remote CI runtime gate.',
  '- Classify failures before repairing: implementation defect, test/CI defect established against the accepted contract, infrastructure, flaky behavior, pre-existing baseline failure, or contract conflict. Do not weaken assertions, delete required checks or lower thresholds just to obtain green. Retry a transient infrastructure failure at most once; stop automatic edits after two failed substantive repairs of the same root cause, or earlier without new diagnostic evidence. Agree time budgets per task. Preserve attempt summaries in existing delivery/checkpoint records across sessions and agents; renaming the issue does not reset the budget. Budget exhaustion leaves work incomplete; renewed work needs an explicit extension. These are workflow instructions, not persisted machine-enforced counters.',
];
