import { createHash } from 'node:crypto';
import {
  lstat,
  mkdir,
  readFile,
  rename,
  rm,
  rmdir,
  writeFile,
} from 'node:fs/promises';
import path from 'node:path';
import { TextDecoder } from 'node:util';
import {
  extractManagedBlock,
  hasManagedBlock,
  removeManagedBlock,
  replaceManagedBlock,
} from './managed-block.js';
import type { PlatformName } from './registry.js';

/**
 * This is the schema of the generated bootstrap, not a product version.  The
 * schema manifest records the expected renderer schema while physical status
 * is derived from the managed files below.
 */
export const V3_ADAPTER_VERSION = '3';

export const V3_ADAPTER_MANAGED_MARKER =
  '<!-- Managed by mancode:continuity-adapter. Do not edit this marker. -->';

export const V3_MODE_ENTRY_MANAGED_MARKER =
  '<!-- Managed by mancode:continuity-mode-entry. Do not edit this marker. -->';

const LEGACY_V3_ADAPTER_MANAGED_MARKER =
  '<!-- Managed by mancode:v3-adapter. Do not edit this marker. -->';
const LEGACY_V3_MODE_ENTRY_MANAGED_MARKER =
  '<!-- Managed by mancode:v3-mode-entry. Do not edit this marker. -->';

export const V3_ADAPTER_DIGEST_DOMAIN = 'mancode-adapter-digest-v1';

export const V3_MODE_NAMES = [
  'manba',
  'man',
  'manteam',
  'manps',
  'mansolo',
] as const;

export type V3ModeName = (typeof V3_MODE_NAMES)[number];

const LEGACY_MODE_ENTRY_MANAGED_MARKERS = [
  LEGACY_V3_MODE_ENTRY_MANAGED_MARKER,
  '<!-- Managed by mancode:claude-skill. Do not edit this marker. -->',
  '<!-- Managed by mancode:codex-skill. Do not edit this file manually. -->',
  '<!-- Managed by mancode:zcode-skill. Do not edit this file manually. -->',
  '<!-- Managed by mancode:mode-file. Do not edit this file manually. -->',
] as const;

const GENERATED_CLAUDE_HOOK_COMMANDS = new Set([
  'node ".mancode/hooks/session-start.mjs"',
  'node ".mancode/hooks/user-prompt-submit.mjs"',
  'bash .mancode/hooks/session-start.sh',
  'bash .mancode/hooks/user-prompt-submit.sh',
]);

const LEGACY_CLAUDE_SKILL_PATHS = new Set([
  '.claude/skills/mancode-solo.md',
  '.claude/skills/mancode-man8.md',
  '.claude/skills/mancode-man.md',
  '.claude/skills/mancode-mansolo.md',
]);

const LEGACY_CLAUDE_SETTINGS_RAW_HINTS = [
  '.mancode/hooks/session-start.',
  '.mancode/hooks/user-prompt-submit.',
  ...LEGACY_CLAUDE_SKILL_PATHS,
] as const;

const CONTINUITY_CLAUDE_START_MARKER =
  '<!-- mancode:continuity:claude:start -->';
const CONTINUITY_CLAUDE_END_MARKER = '<!-- mancode:continuity:claude:end -->';
const V3_CODEX_START_MARKER = '<!-- mancode:continuity:codex:start -->';
const V3_CODEX_END_MARKER = '<!-- mancode:continuity:codex:end -->';
const V3_ZCODE_START_MARKER = '<!-- mancode:continuity:zcode:start -->';
const V3_ZCODE_END_MARKER = '<!-- mancode:continuity:zcode:end -->';
const V3_COPILOT_START_MARKER = '<!-- mancode:continuity:copilot:start -->';
const V3_COPILOT_END_MARKER = '<!-- mancode:continuity:copilot:end -->';
const LEGACY_V3_CODEX_MARKERS = [
  '<!-- mancode:v3:codex:start -->',
  '<!-- mancode:v3:codex:end -->',
] as const;
const LEGACY_V3_ZCODE_MARKERS = [
  '<!-- mancode:v3:zcode:start -->',
  '<!-- mancode:v3:zcode:end -->',
] as const;
const LEGACY_V3_COPILOT_MARKERS = [
  '<!-- mancode:v3:copilot:start -->',
  '<!-- mancode:v3:copilot:end -->',
] as const;
const LEGACY_CODEX_START_MARKER = '<!-- mancode:start -->';
const LEGACY_CODEX_END_MARKER = '<!-- mancode:end -->';
const LEGACY_ZCODE_START_MARKER = '<!-- mancode:zcode:start -->';
const LEGACY_ZCODE_END_MARKER = '<!-- mancode:zcode:end -->';
const RETRIABLE_ADAPTER_READ_CODES = new Set(['EACCES', 'EBUSY', 'EPERM']);
const ADAPTER_READ_MAX_ATTEMPTS = 4;
const ADAPTER_READ_RETRY_DELAY_MS = 25;

export interface V3AdapterCapabilities {
  nativeModeEntry: boolean;
  sessionHook: false;
  promptHook: false;
  sessionIdentity: 'explicit-required';
}

export interface V3PlatformAdapterStatus {
  version: string;
  installed: boolean;
  ready: boolean;
  status: V3AdapterContentStatus;
  target: string;
  detail: string;
  targets: V3AdapterManagedTargetStatus[];
  capabilities: V3AdapterCapabilities;
}

export type V3AdapterContentStatus =
  | 'ready'
  | 'missing'
  | 'stale'
  | 'unreadable';

export interface V3AdapterManagedTargetStatus {
  identity: string;
  target: string;
  status: V3AdapterContentStatus;
  actualDigest: string | null;
  expectedDigest: string;
  rendererVersion: string;
  repair: string;
  detail: string;
}

interface V3AdapterManagedTargetSpec {
  identity: string;
  target: string;
  fileTarget: V3AdapterFileTarget;
  expectedManagedContent: string;
  blockMarkers: readonly [string, string] | null;
}

/**
 * A physical file touched by the V3 bootstrap renderer. Codex and ZCode
 * deliberately share the AGENTS target, so activation journals these files
 * rather than individual platform installs.
 */
export type V3ModeEntryFileTarget =
  | `claude-mode-${V3ModeName}`
  | `agents-mode-${V3ModeName}`
  | `cursor-mode-${V3ModeName}`
  | `copilot-mode-${V3ModeName}`;

export type V3LegacyAdapterFileTarget =
  | 'claude-settings'
  | 'claude-legacy-solo'
  | 'cursor-legacy-context'
  | 'cursor-legacy-practice'
  | 'cursor-legacy-solo'
  | 'cursor-legacy-manba'
  | 'cursor-legacy-man'
  | 'cursor-legacy-manteam'
  | 'cursor-legacy-manps'
  | 'cursor-legacy-mamba'
  | 'cursor-legacy-man8'
  | V3LegacyModeAliasTarget;

type V3LegacyModeAliasTarget =
  | `claude-alias-${LegacyModeAlias}`
  | `agents-alias-${LegacyModeAlias}`
  | `cursor-alias-${LegacyModeAlias}`
  | `copilot-alias-${LegacyModeAlias}`;

type LegacyModeAlias = 'mamba' | 'man8';

export type V3AdapterFileTarget =
  | 'claude-skill'
  | 'cursor-rule'
  | 'agents'
  | 'copilot-instructions'
  | V3ModeEntryFileTarget
  | V3LegacyAdapterFileTarget;

export const V3_ADAPTER_PLATFORMS: readonly PlatformName[] = [
  'claude-code',
  'codex',
  'cursor',
  'copilot',
  'zcode',
];

export interface V3AdapterFilePlan {
  target: V3AdapterFileTarget;
  beforeContent: string | null;
  targetContent: string;
}

export interface V3StagedAdapterFilePlan {
  target: V3AdapterFileTarget;
  stagingTarget: string;
}

export interface V3StagedAdapter {
  platform: PlatformName;
  /** The corresponding live target, relative to the project root. */
  target: string;
  /** The generated candidate, kept under V3 staging rather than the live target. */
  stagingTarget: string;
  /** Original public mode entries staged beside the bootstrap candidate. */
  modeEntries: Array<{
    mode: V3ModeName;
    target: string;
    stagingTarget: string;
  }>;
}

const V3_MODE_ENTRY_FILE_TARGETS = V3_MODE_NAMES.flatMap((mode) => [
  `claude-mode-${mode}` as const,
  `agents-mode-${mode}` as const,
  `cursor-mode-${mode}` as const,
  `copilot-mode-${mode}` as const,
]);

const V3_LEGACY_ADAPTER_FILE_TARGETS: readonly V3LegacyAdapterFileTarget[] = [
  'claude-settings',
  'claude-legacy-solo',
  'cursor-legacy-context',
  'cursor-legacy-practice',
  'cursor-legacy-solo',
  'cursor-legacy-manba',
  'cursor-legacy-man',
  'cursor-legacy-manteam',
  'cursor-legacy-manps',
  'cursor-legacy-mamba',
  'cursor-legacy-man8',
  ...(['mamba', 'man8'] as const).flatMap((mode) => [
    `claude-alias-${mode}` as const,
    `agents-alias-${mode}` as const,
    `cursor-alias-${mode}` as const,
    `copilot-alias-${mode}` as const,
  ]),
];

export const V3_ADAPTER_FILE_TARGETS: readonly V3AdapterFileTarget[] = [
  'claude-skill',
  'cursor-rule',
  'agents',
  'copilot-instructions',
  ...V3_MODE_ENTRY_FILE_TARGETS,
  ...V3_LEGACY_ADAPTER_FILE_TARGETS,
];

/** Computes the content digest for one logical managed target. */
export function adapterManagedContentDigest(
  targetIdentity: string,
  managedContent: string | Uint8Array,
): string {
  if (!targetIdentity.trim() || targetIdentity.includes('\0')) {
    throw new Error('MANCODE_V3_ADAPTER_TARGET_IDENTITY_INVALID');
  }
  const content =
    typeof managedContent === 'string'
      ? Buffer.from(managedContent, 'utf8')
      : Buffer.from(managedContent);
  const digest = createHash('sha256')
    .update(Buffer.from(V3_ADAPTER_DIGEST_DOMAIN, 'utf8'))
    .update(Buffer.from([0]))
    .update(Buffer.from(targetIdentity, 'utf8'))
    .update(Buffer.from([0]))
    .update(content)
    .digest('hex');
  return `sha256:${digest}`;
}

/**
 * Calculates exact file replacements without publishing them. This lets a
 * migration journal bind the combined AGENTS.md result before its first
 * visible write and preserves all user-authored content outside our blocks.
 */
export async function planV3AdapterFiles(
  projectRoot: string,
): Promise<V3AdapterFilePlan[]> {
  const root = path.resolve(projectRoot);
  const existing = new Map<V3AdapterFileTarget, string | null>();
  for (const target of V3_ADAPTER_FILE_TARGETS) {
    existing.set(target, await readAdapterTarget(root, target));
  }
  const agents = removeLegacyV3Block(
    removeLegacyV3Block(
      removeLegacyAgentsBlocks(existing.get('agents') ?? ''),
      LEGACY_V3_CODEX_MARKERS,
    ),
    LEGACY_V3_ZCODE_MARKERS,
  );
  const nextAgents = replaceManagedV3BlockText(
    replaceManagedV3BlockText(
      agents,
      V3_CODEX_START_MARKER,
      V3_CODEX_END_MARKER,
      renderV3Bootstrap('codex'),
    ),
    V3_ZCODE_START_MARKER,
    V3_ZCODE_END_MARKER,
    renderV3Bootstrap('zcode'),
  );
  const legacyAdapterPlans = planLegacyAdapterRetirement(existing);
  const plans: V3AdapterFilePlan[] = [
    {
      target: 'claude-skill',
      beforeContent: existing.get('claude-skill') ?? null,
      targetContent: replaceManagedV3BlockText(
        existing.get('claude-skill') ?? '',
        CONTINUITY_CLAUDE_START_MARKER,
        CONTINUITY_CLAUDE_END_MARKER,
        renderV3Bootstrap('claude-code'),
      ),
    },
    managedFilePlan(
      'cursor-rule',
      existing.get('cursor-rule') ?? null,
      renderCursorRule(renderV3Bootstrap('cursor')),
    ),
    {
      target: 'agents',
      beforeContent: existing.get('agents') ?? null,
      targetContent: nextAgents,
    },
    {
      target: 'copilot-instructions',
      beforeContent: existing.get('copilot-instructions') ?? null,
      targetContent: replaceManagedV3BlockText(
        removeLegacyV3Block(
          removeManagedBlock(existing.get('copilot-instructions') ?? ''),
          LEGACY_V3_COPILOT_MARKERS,
        ),
        V3_COPILOT_START_MARKER,
        V3_COPILOT_END_MARKER,
        renderV3Bootstrap('copilot'),
      ),
    },
    ...V3_MODE_ENTRY_FILE_TARGETS.map((target) =>
      managedModeEntryPlan(
        target,
        existing.get(target) ?? null,
        renderModeEntryForFileTarget(target),
      ),
    ),
    ...legacyAdapterPlans,
  ];
  return plans;
}

/** Plans a selected-platform repair while composing shared AGENTS targets once. */
export async function planV3AdapterUpgradeFiles(
  projectRoot: string,
  platforms: readonly PlatformName[],
): Promise<V3AdapterFilePlan[]> {
  const root = path.resolve(projectRoot);
  const selected = normalizeUpgradePlatforms(platforms);
  const targetSet = new Set<V3AdapterFileTarget>();
  for (const platform of selected) {
    targetSet.add(primaryFileTarget(platform));
    for (const mode of V3_MODE_NAMES) {
      targetSet.add(modeEntryFileTarget(platform, mode));
    }
    for (const target of legacyAdapterTargetsForPlatform(platform, true)) {
      targetSet.add(target);
    }
  }
  const existing = new Map<V3AdapterFileTarget, string | null>();
  for (const target of targetSet) {
    existing.set(target, await readAdapterTarget(root, target));
  }
  const desired = new Map(existing);
  for (const platform of selected) {
    planPlatformBootstrapUpgrade(desired, platform);
    for (const mode of V3_MODE_NAMES) {
      const target = modeEntryFileTarget(platform, mode);
      const current = desired.get(target) ?? null;
      desired.set(
        target,
        managedModeEntryPlan(target, current, renderV3ModeEntry(mode, platform))
          .targetContent,
      );
    }
  }
  const plans = [...desired.entries()]
    .filter(([target, targetContent]) => existing.get(target) !== targetContent)
    .map(([target, targetContent]) => ({
      target,
      beforeContent: existing.get(target) ?? null,
      targetContent: targetContent ?? '',
    }));
  const legacyPlans = planLegacyAdapterRetirement(existing).filter(
    (legacyPlan) =>
      !plans.some((candidate) => candidate.target === legacyPlan.target),
  );
  return [...plans, ...legacyPlans];
}

/** Writes immutable upgrade candidates below .mancode staging, never live targets. */
export async function stageV3AdapterUpgradeFiles(
  projectRoot: string,
  operationId: string,
  plans: readonly V3AdapterFilePlan[],
): Promise<V3StagedAdapterFilePlan[]> {
  if (!/^[0-7][0-9A-HJKMNP-TV-Z]{25}$/.test(operationId)) {
    throw new Error('MANCODE_ADAPTER_UPGRADE_OPERATION_ID_INVALID');
  }
  const root = path.resolve(projectRoot);
  const staged: V3StagedAdapterFilePlan[] = [];
  for (const plan of plans) {
    const liveTarget = v3AdapterTargetPath(root, plan.target);
    const relative = relativeAdapterPath(root, liveTarget);
    const stagingTarget = path.join(
      '.mancode',
      'staging',
      'adapters',
      'upgrade',
      operationId,
      relative,
    );
    const destination = path.join(root, stagingTarget);
    await assertAdapterPathSafe(root, destination);
    await mkdir(path.dirname(destination), { recursive: true });
    await atomicWrite(destination, plan.targetContent);
    staged.push({
      target: plan.target,
      stagingTarget: relativeAdapterPath(root, destination),
    });
  }
  return staged;
}

/** Publishes one precomputed fixed-target replacement with atomic rename. */
export async function applyV3AdapterFilePlan(
  projectRoot: string,
  plan: V3AdapterFilePlan,
): Promise<void> {
  const root = path.resolve(projectRoot);
  if (!V3_ADAPTER_FILE_TARGETS.includes(plan.target)) {
    throw new Error('MANCODE_V3_ADAPTER_TARGET_INVALID');
  }
  if (typeof plan.targetContent !== 'string' || !plan.targetContent.trim()) {
    throw new Error('MANCODE_V3_ADAPTER_TARGET_INVALID');
  }
  const target = v3AdapterTargetPath(root, plan.target);
  await assertAdapterPathSafe(root, target);
  const retiredBootstrapPlatform = retiredBootstrapPlatformFor(plan.target);
  if (retiredBootstrapPlatform !== null) {
    for (const retired of retiredBootstrapSpecs(
      root,
      retiredBootstrapPlatform,
    )) {
      await assertAdapterPathSafe(root, retired.filePath);
    }
  }
  const current = await readAdapterTarget(root, plan.target);
  if (current === plan.targetContent) {
    if (retiredBootstrapPlatform !== null) {
      await removeRetiredBootstrapFiles(root, retiredBootstrapPlatform);
    }
    return;
  }
  if (current !== plan.beforeContent) {
    throw new Error('MANCODE_V3_ADAPTER_TARGET_CONFLICT');
  }
  await mkdir(path.dirname(target), { recursive: true });
  await atomicWrite(target, plan.targetContent);
  if (retiredBootstrapPlatform !== null) {
    // The old bootstrap is non-authoritative and is retired only after its
    // Continuity replacement is durable. A later repair safely retries this.
    await removeRetiredBootstrapFiles(root, retiredBootstrapPlatform);
  }
}

/**
 * Renders a complete adapter candidate under Continuity staging. Shadow integration
 * may inspect this exact replacement without changing a live managed file.
 */
export async function stageV3Adapter(
  projectRoot: string,
  platform: PlatformName,
): Promise<V3StagedAdapter> {
  const root = path.resolve(projectRoot);
  await assertPlatformAdapterPathsSafe(root, platform);
  const target = targetFor(platform);
  const content = await renderV3AdapterCandidate(root, platform);
  const stagingTarget = path.join(
    '.mancode',
    'staging',
    'adapters',
    'continuity',
    platform,
    target,
  );
  const destination = path.join(root, stagingTarget);
  await assertAdapterPathSafe(root, destination);
  await mkdir(path.dirname(destination), { recursive: true });
  await atomicWrite(destination, content);
  const modeEntries = [] as V3StagedAdapter['modeEntries'];
  for (const mode of V3_MODE_NAMES) {
    const modeTarget = path.relative(
      root,
      v3ModeEntryPath(root, platform, mode),
    );
    const modeStagingTarget = path.join(
      '.mancode',
      'staging',
      'adapters',
      'continuity',
      platform,
      modeTarget,
    );
    const modeDestination = path.join(root, modeStagingTarget);
    await assertAdapterPathSafe(root, modeDestination);
    await mkdir(path.dirname(modeDestination), { recursive: true });
    await atomicWrite(modeDestination, renderV3ModeEntry(mode, platform));
    modeEntries.push({
      mode,
      target: modeTarget,
      stagingTarget: modeStagingTarget,
    });
  }
  return { platform, target, stagingTarget, modeEntries };
}

export function v3AdapterTargetPath(
  projectRoot: string,
  target: V3AdapterFileTarget,
): string {
  const root = path.resolve(projectRoot);
  const modeTarget = parseModeEntryFileTarget(target);
  if (modeTarget !== null) {
    return v3ModeEntryPath(root, modeTarget.platform, modeTarget.mode);
  }
  const legacyTarget = legacyAdapterRelativePath(target);
  if (legacyTarget !== null) return path.join(root, legacyTarget);
  switch (target) {
    case 'claude-skill':
      return path.join(root, 'CLAUDE.md');
    case 'cursor-rule':
      return path.join(root, '.cursor', 'rules', 'mancode-continuity.mdc');
    case 'agents':
      return path.join(root, 'AGENTS.md');
    case 'copilot-instructions':
      return path.join(root, '.github', 'copilot-instructions.md');
  }
  throw new Error('MANCODE_V3_ADAPTER_TARGET_INVALID');
}

/** Validates every existing segment before a recovery read or removal. */
export async function assertV3AdapterTargetSafe(
  projectRoot: string,
  target: V3AdapterFileTarget,
): Promise<void> {
  const root = path.resolve(projectRoot);
  await assertAdapterPathSafe(root, v3AdapterTargetPath(root, target));
}

/** The original public mode name, rendered at the host's native entry path. */
export function v3ModeEntryPath(
  projectRoot: string,
  platform: PlatformName,
  mode: V3ModeName,
): string {
  const root = path.resolve(projectRoot);
  switch (platform) {
    case 'claude-code':
      return path.join(root, '.claude', 'skills', mode, 'SKILL.md');
    case 'codex':
    case 'zcode':
      return path.join(root, '.agents', 'skills', mode, 'SKILL.md');
    case 'cursor':
      return path.join(root, '.cursor', 'commands', `${mode}.md`);
    case 'copilot':
      return path.join(root, '.github', 'prompts', `${mode}.prompt.md`);
  }
}

/**
 * Writes only stable V3 bootstrap instructions.  In particular, this never
 * creates legacy authority or copies task state into an adapter file.
 */
export async function installV3Adapter(
  projectRoot: string,
  platform: PlatformName,
): Promise<V3PlatformAdapterStatus> {
  const root = path.resolve(projectRoot);
  await assertV3AdapterInstallable(root, platform);
  const content = renderV3Bootstrap(platform);
  switch (platform) {
    case 'claude-code':
      await replaceManagedV3Block(
        path.join(root, 'CLAUDE.md'),
        CONTINUITY_CLAUDE_START_MARKER,
        CONTINUITY_CLAUDE_END_MARKER,
        content,
      );
      await removeRetiredBootstrapFiles(root, platform);
      break;
    case 'cursor':
      await writeManagedFile(
        path.join(root, '.cursor', 'rules', 'mancode-continuity.mdc'),
        renderCursorRule(content),
      );
      await removeRetiredBootstrapFiles(root, platform);
      break;
    case 'codex':
      await replaceManagedV3Block(
        path.join(root, 'AGENTS.md'),
        V3_CODEX_START_MARKER,
        V3_CODEX_END_MARKER,
        content,
        [
          LEGACY_V3_CODEX_MARKERS,
          [LEGACY_CODEX_START_MARKER, LEGACY_CODEX_END_MARKER],
          [LEGACY_ZCODE_START_MARKER, LEGACY_ZCODE_END_MARKER],
        ],
      );
      break;
    case 'copilot':
      await replaceManagedV3Block(
        path.join(root, '.github', 'copilot-instructions.md'),
        V3_COPILOT_START_MARKER,
        V3_COPILOT_END_MARKER,
        content,
        [
          LEGACY_V3_COPILOT_MARKERS,
          [LEGACY_CODEX_START_MARKER, LEGACY_CODEX_END_MARKER],
        ],
      );
      break;
    case 'zcode':
      await replaceManagedV3Block(
        path.join(root, 'AGENTS.md'),
        V3_ZCODE_START_MARKER,
        V3_ZCODE_END_MARKER,
        content,
        [
          LEGACY_V3_ZCODE_MARKERS,
          [LEGACY_CODEX_START_MARKER, LEGACY_CODEX_END_MARKER],
          [LEGACY_ZCODE_START_MARKER, LEGACY_ZCODE_END_MARKER],
        ],
      );
      break;
  }
  await retireLegacyPlatformFiles(root, platform);
  for (const mode of V3_MODE_NAMES) {
    await writeV3ModeEntry(
      v3ModeEntryPath(root, platform, mode),
      renderV3ModeEntry(mode, platform),
    );
  }
  return inspectV3Adapter(root, platform);
}

/**
 * Proves all deterministic adapter writes are safe before initialization or
 * repair publishes its first file. I/O can still fail later, but user-owned
 * targets, malformed managed settings, and unsafe paths cannot leave a known
 * partial install behind.
 */
export async function assertV3AdapterInstallable(
  projectRoot: string,
  platform: PlatformName,
): Promise<void> {
  const root = path.resolve(projectRoot);
  await assertPlatformAdapterPathsSafe(root, platform);
  await assertV3ModeEntriesWritable(root, platform);
  await renderV3AdapterCandidate(root, platform);

  const existing = new Map<V3AdapterFileTarget, string | null>();
  for (const target of legacyAdapterTargetsForPlatform(platform, true)) {
    existing.set(target, await readAdapterTarget(root, target));
  }
  planLegacyAdapterRetirement(existing);
}

/** Physical adapter status intentionally does not infer hook approval. */
export async function inspectV3Adapter(
  projectRoot: string,
  platform: PlatformName,
): Promise<V3PlatformAdapterStatus> {
  const root = path.resolve(projectRoot);
  const target = targetFor(platform);
  const targets: V3AdapterManagedTargetStatus[] = [];
  for (const spec of managedTargetSpecs(root, platform)) {
    targets.push(await inspectManagedTarget(root, platform, spec));
  }
  const ready = targets.every((item) => item.status === 'ready');
  const installed = targets.every((item) => item.status !== 'missing');
  const status = aggregateAdapterStatus(targets);
  return {
    version: V3_ADAPTER_VERSION,
    installed,
    ready,
    status,
    target,
    detail:
      status === 'ready'
        ? 'Managed adapter content matches the current renderer.'
        : status === 'missing'
          ? 'One or more managed adapter targets are missing.'
          : status === 'stale'
            ? 'Managed adapter content differs from the current renderer.'
            : 'One or more managed adapter targets cannot be read safely.',
    targets,
    capabilities: capabilitiesFor(platform),
  };
}

/** Actual on-disk inventory for compatibility gates; never trust manifest echo. */
export async function inspectV3AdapterVersions(
  projectRoot: string,
  requiredPlatforms: readonly PlatformName[] = [],
): Promise<Partial<Record<PlatformName, string>>> {
  const platforms: PlatformName[] = [
    'claude-code',
    'codex',
    'cursor',
    'copilot',
    'zcode',
  ];
  const required = new Set(requiredPlatforms);
  const entries = await Promise.all(
    platforms.map(
      async (platform) =>
        [platform, await inspectV3Adapter(projectRoot, platform)] as const,
    ),
  );
  return v3AdapterVersionsFromStatuses(entries, required);
}

/** Builds the same physical inventory used by compatibility from prior status reads. */
export function v3AdapterVersionsFromStatuses(
  entries: ReadonlyArray<readonly [PlatformName, V3PlatformAdapterStatus]>,
  requiredPlatforms: ReadonlySet<PlatformName> | readonly PlatformName[] = [],
): Partial<Record<PlatformName, string>> {
  const required =
    requiredPlatforms instanceof Set
      ? requiredPlatforms
      : new Set(requiredPlatforms);
  const versions = entries.map(([platform, status]) => {
    const primaryPresent = status.targets[0]?.status !== 'missing';
    return required.has(platform) || primaryPresent
      ? ([platform, status.ready ? status.version : status.status] as const)
      : null;
  });
  return Object.fromEntries(
    versions.filter(
      (entry): entry is NonNullable<typeof entry> => entry !== null,
    ),
  ) as Partial<Record<PlatformName, string>>;
}

/** Removes only the V3 bootstrap owned by this renderer, never V3 authority. */
export async function removeV3Adapter(
  projectRoot: string,
  platform: PlatformName,
): Promise<void> {
  const root = path.resolve(projectRoot);
  await assertPlatformAdapterPathsSafe(root, platform);
  let preserveSharedModeEntries = false;
  switch (platform) {
    case 'claude-code':
      await removeManagedV3Block(
        path.join(root, 'CLAUDE.md'),
        CONTINUITY_CLAUDE_START_MARKER,
        CONTINUITY_CLAUDE_END_MARKER,
      );
      await removeRetiredBootstrapFiles(root, platform);
      break;
    case 'cursor':
      await removeManagedFile(
        path.join(root, '.cursor', 'rules', 'mancode-continuity.mdc'),
      );
      await removeRetiredBootstrapFiles(root, platform);
      break;
    case 'codex':
      await removeManagedV3Block(
        path.join(root, 'AGENTS.md'),
        V3_CODEX_START_MARKER,
        V3_CODEX_END_MARKER,
      );
      await removeManagedV3Block(
        path.join(root, 'AGENTS.md'),
        ...LEGACY_V3_CODEX_MARKERS,
      );
      preserveSharedModeEntries = await anyManagedBlockPresent(
        path.join(root, 'AGENTS.md'),
        [[V3_ZCODE_START_MARKER, V3_ZCODE_END_MARKER], LEGACY_V3_ZCODE_MARKERS],
      );
      break;
    case 'copilot':
      await removeManagedV3Block(
        path.join(root, '.github', 'copilot-instructions.md'),
        V3_COPILOT_START_MARKER,
        V3_COPILOT_END_MARKER,
      );
      await removeManagedV3Block(
        path.join(root, '.github', 'copilot-instructions.md'),
        ...LEGACY_V3_COPILOT_MARKERS,
      );
      break;
    case 'zcode':
      await removeManagedV3Block(
        path.join(root, 'AGENTS.md'),
        V3_ZCODE_START_MARKER,
        V3_ZCODE_END_MARKER,
      );
      await removeManagedV3Block(
        path.join(root, 'AGENTS.md'),
        ...LEGACY_V3_ZCODE_MARKERS,
      );
      preserveSharedModeEntries = await anyManagedBlockPresent(
        path.join(root, 'AGENTS.md'),
        [[V3_CODEX_START_MARKER, V3_CODEX_END_MARKER], LEGACY_V3_CODEX_MARKERS],
      );
      break;
  }
  if (!preserveSharedModeEntries) {
    for (const mode of V3_MODE_NAMES) {
      await removeV3ModeEntry(v3ModeEntryPath(root, platform, mode));
    }
  }
  await removeRetiredLegacyPlatformFiles(root, platform);
}

export function renderV3Bootstrap(platform: PlatformName): string {
  const platformLabel = platformLabelFor(platform);
  const sessionArguments = sessionArgumentsFor(platform);
  const sessionCreationGuidance =
    platform === 'codex' || platform === 'zcode'
      ? 'When status has no `session`, first reuse any explicit session ID already returned in this conversation. Only when neither exists, create one once with `mancode context session new --client codex` in Codex or `mancode context session new --client zcode` in ZCode.'
      : `When status has no \`session\`, first reuse any explicit session ID already returned in this conversation. Only when neither exists, create one once with \`mancode context session new --client ${platform}\`.`;
  const spikePlatform =
    platform === 'codex' || platform === 'zcode'
      ? 'the active Codex or ZCode host'
      : platform;
  const modeEntry = capabilitiesFor(platform).nativeModeEntry
    ? 'Use the platform mode entry only as a shortcut; resolve a Context Pack first.'
    : 'This platform has no native mancode mode entry; use the CLI commands explicitly.';
  return [
    '# mancode bootstrap',
    '',
    V3_ADAPTER_MANAGED_MARKER,
    '',
    `- Platform: ${platformLabel}. This file is a non-authoritative bootstrap.`,
    '- Locate the project root before running mancode commands.',
    '- Before the first command, choose one CLI binary for the entire task: use `./node_modules/.bin/mancode` when it exists, otherwise use `mancode`. Run that selected binary with `--version` once and never mix binaries or versions.',
    '- In every command below, `mancode` means that selected binary; when the local binary exists, invoke the command as `./node_modules/.bin/mancode ...` rather than falling back to a global executable.',
    '- Reuse a `mancode status --brief --json` snapshot already obtained in this conversation. Only when no such snapshot exists, run it once from the project root.',
    '- Inspect a session read-only with `mancode context session show --session <id> --client <client> --json`; do not invent other session subcommands.',
    '- The compact status is the public mancode Continuity runtime view. In operator-facing narration, say `mancode` or `mancode Continuity`; never prefix a mode or action with a version label.',
    '- An explicitly invoked original `man`, `manba`, `manteam`, `manps`, or `mansolo` entry supplies its authorized action. Its mode-specific steps override conflicting generic no-task or mutation guidance below.',
    '- In particular, `manps` may run local health scans without an actor, session, or TaskRef. `mansolo` needs them only for an explicit governed handoff.',
    '- Outside an explicitly invoked mode entry, treat an ordinary requested coding task as default Solo work. Ordinary Solo work requires no actor identity, session, TaskRef, or workflow; do not ask for a display name or create Continuity authority for it.',
    "- Before editing in default Solo, inspect only the relevant project facts, implementation, tests, and contracts. A supplied instruction is not automatically sound: verify its factual assumptions and proposed solution against the repository and the operator's goal.",
    '- If the goal and decision-changing requirements are clear, consistent with project evidence, and low risk, proceed with the narrowest useful change without ceremonial questions. Resolve repository-answerable unknowns yourself.',
    '- When the goal is clear but requirements are incomplete, classify each remaining unknown as blocking, recommendable, or defaultable. Ask and wait only for blocking decisions that can materially change behavior, scope, acceptance, architecture, data, security, compatibility, or semantic ownership. For recommendable decisions, give bounded options and a clear recommendation. Use a default only when it is low-impact, reversible, consistent with repository conventions, and stated explicitly.',
    "- If an explicit request conflicts with repository evidence or introduces a hard-risk change involving authentication, payment, sensitive data, deletion, migration, public APIs, untrusted input, concurrency, infrastructure, or another irreversible effect, stop before editing. Show the concrete conflict or impact, recommend the safer path, ask a focused confirmation or choice, and wait. Clarity never overrides safety or the operator's actual goal.",
    '- A natural-language request explicitly asking for research, a plan, architecture, migration design, or formal acceptance authorizes the `man` planning path without a separate mode-confirmation question. For an ordinary implementation request whose blocking decision crosses modules or requires architecture, migration, semantic owner/source-of-truth, team coordination, or formal acceptance, recommend `/man`, explain why, and wait; never switch authority silently.',
    '- For governed task work only, if status has no `identity.actorId`, ask for a display name and run `mancode team identity create --name "<display name>"` before creating a session.',
    '- If status reports `session`, reuse it. `task: null` and `MANCODE_TASK_REQUIRED` do not make a session stale.',
    `- ${sessionCreationGuidance} Pass its returned \`sessionId\` and matching client as \`${sessionArguments}\` to every later session command; an \`export\` inside one command tool does not persist to later command tools.`,
    '- Outside an invoked original mode entry, if no coding, planning, diagnostic, or review task was requested and no TaskRef is explicitly supplied, report "no task bound" and stop. Do not probe workflow subcommands to work around `MANCODE_TASK_REQUIRED`.',
    '- Bootstrap discovery is read-only: before the operator explicitly requests task work, do not run `mancode init`, `mancode migrate`, `mancode workflow`, or inspect mancode installed package/source.',
    `- With an existing or explicitly supplied TaskRef, read its Context Pack with \`mancode context show --purpose orient ${sessionArguments}\`; for anonymous diagnosis, include an explicit \`--task <namespace:id>\`. A plain-language Solo request is not a TaskRef and needs no Context Pack.`,
    '- After an operator explicitly requests task work, perform mutations only through `mancode workflow`, `mancode team`, and `mancode context` commands with their required revision and session arguments.',
    '- For a mode entry, request the matching Context Pack purpose: `plan`, `implement`, `review`, `verify`, or `handoff`.',
    '- Do not persist task, mode, or session state in this adapter file or any legacy state file.',
    `- ${modeEntry}`,
    `- No approved session or prompt hook is assumed. After a real-host spike is recorded for ${spikePlatform}, a verified host may provide MANCODE_HOST_SESSION_KEY; otherwise mutations require an explicit \`--session\`.`,
  ].join('\n');
}

/**
 * One renderer backs every original mode name. The entry contains navigation
 * only; V3 stores remain the sole authority for sessions, tasks, and workflow
 * revisions.
 */
export function renderV3ModeEntry(
  mode: V3ModeName,
  platform: PlatformName,
): string {
  const definition = V3_MODE_DEFINITIONS[mode];
  const sessionArguments = sessionArgumentsFor(platform);
  const sessionClientGuidance = sessionClientGuidanceFor(platform);
  const statusGuidance =
    'Reuse a `mancode status --brief --json` snapshot already obtained in this conversation. Only when none exists, run it once from the project root.';
  const cliSelectionGuidance =
    'Before the first command, use `./node_modules/.bin/mancode` when it exists, otherwise `mancode`; check that selected binary with `--version` once and never mix binaries or versions. In every command below, replace the literal `mancode` with that selected binary path when the local binary exists.';
  const sessionCreationGuidance =
    platform === 'codex' || platform === 'zcode'
      ? 'If status has no current session, reuse an explicit session ID already retained in this conversation. Only if neither exists, run `mancode context session new --client codex` in Codex or `mancode context session new --client zcode` in ZCode exactly once, then retain the returned session ID.'
      : `If status has no current session, reuse an explicit session ID already retained in this conversation. Only if neither exists, run \`mancode context session new --client ${platform}\` exactly once and retain the returned session ID.`;
  let authoritySteps: string[];
  if (mode === 'manps') {
    authoritySteps = [
      `1. ${statusGuidance} Require an active, ready mancode Continuity runtime.`,
      '2. Run the health action below directly. A local scan needs no TaskRef, actor identity, or explicit session.',
      '3. Never read or write legacy mode authority before or after the scan.',
    ];
  } else if (mode === 'mansolo') {
    authoritySteps = [
      `1. ${statusGuidance} Never read or write legacy mode authority.`,
      '2. If no governed task is being handed off, continue with focused solo work without creating a persistent mode, actor, session, or TaskRef.',
      `3. For an explicit governed handoff, ensure \`identity.actorId\`, reuse or create the current session, and bind the existing TaskRef. ${sessionCreationGuidance} ${sessionClientGuidance}`,
      `4. For that governed task only, read \`mancode context show --purpose implement ${sessionArguments}\` using the bound or explicit TaskRef.`,
    ];
  } else if (mode === 'man') {
    authoritySteps = [
      `1. ${statusGuidance} Never read or write the legacy authority file.`,
      '2. If the request is only a read-only project orientation, introduction, explanation, or summary, inspect the repository and answer directly without creating an actor, session, TaskRef, or workflow. Do not turn an orientation request into a `plan_only` workflow.',
      '3. Only for requested governed task work, if `identity.actorId` is absent, ask for a display name and run `mancode team identity create --name "<display name>"`.',
      `4. Reuse \`session.sessionId\` when present. ${sessionCreationGuidance} ${sessionClientGuidance}`,
      `5. Reuse the current TaskRef. To bind a supplied existing task, run \`mancode context resume <namespace:ULID> ${sessionArguments}\`.`,
      `6. For an existing task, read only the needed Context Pack with \`mancode context show --purpose ${definition.contextPurpose} ${sessionArguments}\`; include \`--task <namespace:ULID>\` when it is not yet bound. For a new task, create it through the mode action first, then read the returned TaskRef's Context Pack.`,
    ];
  } else {
    authoritySteps = [
      `1. ${statusGuidance} Never read or write the legacy authority file.`,
      '2. If `identity.actorId` is absent, ask for a display name and run `mancode team identity create --name "<display name>"`.',
      `3. Reuse \`session.sessionId\` when present. ${sessionCreationGuidance} ${sessionClientGuidance}`,
      `4. Reuse the current TaskRef. To bind a supplied existing task, run \`mancode context resume <namespace:ULID> ${sessionArguments}\`.`,
      `5. For an existing task, read only the needed Context Pack with \`mancode context show --purpose ${definition.contextPurpose} ${sessionArguments}\`; include \`--task <namespace:ULID>\` when it is not yet bound. For a new task, create it through the mode action first, then read the returned TaskRef's Context Pack.`,
    ];
  }
  const frontmatter = [
    '---',
    ...(platform === 'claude-code' ||
    platform === 'codex' ||
    platform === 'zcode'
      ? [`name: ${mode}`]
      : []),
    ...(platform === 'copilot' ? ["agent: 'agent'"] : []),
    `description: ${JSON.stringify(definition.description)}`,
    '---',
  ];
  const mutationGuidance =
    mode === 'manps'
      ? 'The local scan and an explicitly requested remediation do not require a TaskRef, workflow revision, actor, or session. Never turn their report files into workflow authority.'
      : mode === 'mansolo'
        ? 'Only an explicit governed handoff mutation requires the bound TaskRef, explicit session, and latest expected revision. Ordinary focused solo work persists no mode state.'
        : 'For every mutation, use the TaskRef, explicit session, matching client, and latest expected revision reported by mancode. Do not emulate the legacy `--step` protocol or persist mode state in an adapter file.';
  const actions = definition.actions.map((action) =>
    action.replaceAll('--session <id>', sessionArguments),
  );
  return [
    ...frontmatter,
    '',
    V3_MODE_ENTRY_MANAGED_MARKER,
    '',
    `# mancode mode: ${mode}`,
    '',
    `Purpose: ${definition.purpose}.`,
    '',
    '## Enter through mancode',
    '',
    cliSelectionGuidance,
    ...authoritySteps,
    '',
    '## Mode action',
    '',
    ...actions,
    '',
    'Treat the compact status as the public mancode Continuity runtime view. In operator-facing narration, say `mancode` or `mancode Continuity`; never prefix this mode or its actions with a version label.',
    '',
    mutationGuidance,
    '',
  ].join('\n');
}

function sessionArgumentsFor(platform: PlatformName): string {
  const client =
    platform === 'codex' || platform === 'zcode' ? '<active-client>' : platform;
  return `--session <id> --client ${client}`;
}

function sessionClientGuidanceFor(platform: PlatformName): string {
  return platform === 'codex' || platform === 'zcode'
    ? 'Use `--client codex` in Codex or `--client zcode` in ZCode on every command that uses this session.'
    : `Use \`--client ${platform}\` on every command that uses this session.`;
}

const V3_MODE_DEFINITIONS: Record<
  V3ModeName,
  {
    description: string;
    purpose: string;
    contextPurpose:
      | 'orient'
      | 'plan'
      | 'implement'
      | 'review'
      | 'verify'
      | 'handoff';
    actions: string[];
  }
> = {
  man: {
    description: 'Plan and execute governed work through mancode.',
    purpose: 'clarify, plan, implement, verify, and review governed work',
    contextPurpose: 'plan',
    actions: [
      '- For a read-only project orientation, inspect and answer directly; do not create governance records.',
      '- For a new task, run `mancode workflow create man "<task>" --session <id>`.',
      '- Before writing requirements, inspect the relevant project facts and implementation, then run a decision-readiness gate covering both clarity and soundness. Treat the request as ready only when the goal, in-scope/out-of-scope behavior, acceptance boundary, semantic owner/source of truth, and decision-changing constraints are supplied and consistent with evidence, verifiable from the repository, or explicitly recorded as safe defaults. A supplied instruction is not automatically correct. Do not ask ceremonial questions or manufacture alternatives when the request is already clear and sound.',
      '- Classify unresolved decisions as blocking, recommendable, or defaultable. Ask and wait for blocking decisions; for recommendable decisions, present 2–3 bounded options with tradeoffs and one clear recommendation; use a default only when it is low-impact, reversible, consistent with repository conventions, and recorded with its reason.',
      '- If any unresolved ambiguity could change the goal, scope, user-visible behavior, acceptance, architecture, data, security, compatibility, owner, or source of truth, stop before requirements finalization, explain the missing decision, ask focused questions, and wait for the user answer. Ask in as many batches as needed, do not repeat answered questions, and never turn an unverified assumption into confirmed scope or confirmed coverage.',
      '- Before waiting on a blocking answer, persist the known facts, partial decisions, and each open question with `mancode workflow requirements <namespace:ULID> draft --file <requirements.json> --expected-revision <n> --session <id>`. A draft may leave scope, coverage, technical decisions, or acceptance incomplete only while `blockingUnknowns` names the open decisions. After every answer, update the draft or finalize it so another session can resume the exact clarification state.',
      '- If an explicit direction conflicts with repository evidence or creates a hard-risk authentication, payment, sensitive-data, deletion, migration, public-API, untrusted-input, concurrency, infrastructure, or irreversible change, stop before requirements finalization. Show the evidence and impact, recommend a safer path, ask for a focused confirmation or choice, and wait; clarity does not waive risk.',
      '- After the user answers, summarize the resolved requirements and any remaining defaults. Continue only when no decision-changing blocking unknown remains; otherwise keep the task in clarification and ask again.',
      '- Write requirements as semantic JSON with `version: 1`, a non-empty `goal`, non-empty `confirmedScope`, and the arrays `excludedScope`, `technicalDecisions`, `defaults`, and `blockingUnknowns`. Every array item must be a non-empty string; an array may be empty except `confirmedScope`, and `technicalDecisions` must be non-empty whenever `technical_stack` applies.',
      '- `coverage` must contain exactly one item for each dimension: `platform`, `core_scope`, `technical_stack`, `data_and_persistence`, `performance`, `compatibility`, and `security`. Each item has the shape `{ "dimension": "platform", "status": "confirmed", "rationale": "..." }`; `status` is exactly `confirmed`, `defaulted`, or `not_applicable`, and `rationale` is non-empty.',
      '- `acceptanceCriteria` must contain at least one required item shaped as `{ "id": "AC-1", "description": "...", "required": true, "method": "automated" }`; `method` is exactly `automated`, `manual`, or `hybrid`.',
      '- Finalize requirements with `mancode workflow requirements <namespace:ULID> finalize --file <requirements.json> --expected-revision <n> --session <id>`.',
      '- Let mancode assign internal IDs and digests; do not invent canonical IDs or digests in the semantic input.',
      '- Revise the plan with `mancode workflow plan <namespace:ULID> revise --expected-revision <n> --file <plan.md> --session <id>`.',
      '- Confirm the current plan with `mancode workflow plan <namespace:ULID> confirm --expected-revision <n> --plan-decision <plan_only|governed_execution> --session <id>`.',
      "- Confirming with `--plan-decision plan_only` keeps the plan as planned authority and clears this session's active workflow pointer. Resume the TaskRef explicitly before any later governed mutation.",
      '- When new evidence materially invalidates confirmed requirements and the operator explicitly chooses to realign the same local task, resume its TaskRef if needed, generate a fresh canonical checkpoint ULID, and run `mancode workflow reframe <namespace:ULID> --expected-revision <n> --checkpoint-id <fresh-ULID> --summary "<reason>" --next-action "<step-2 action>" --session <id>`. Reframe archives the confirmed requirements and plan, clears the plan decision, and stops at Step 2 with draft requirements. Do not substitute plan revise, scope-change, or workflow update for reframe.',
      '- Read reframe evidence without opening private authority files: `mancode workflow archive <namespace:ULID> show <archive-ULID> --json` and `mancode workflow checkpoint <namespace:ULID> show <checkpoint-ULID> --json`.',
      '- Apply verification and review ledgers with their mancode `apply --file` commands, then use `mancode workflow complete <namespace:ULID> --expected-revision <n> --session <id>`.',
    ],
  },
  manba: {
    description: 'Diagnose and verify a bug through mancode.',
    purpose: 'reproduce, diagnose, fix, and verify a regression',
    contextPurpose: 'implement',
    actions: [
      '- For a new diagnostic task, run `mancode workflow create manba "<task>" --session <id>`.',
      '- Before changing code, establish the expected behavior from reproducible evidence, tests, documentation, history, or the current semantic owner. If the bug goal is clear but the correct behavior cannot be established, ask one focused question and wait instead of inventing product behavior.',
      '- If the requested fix conflicts with repository evidence or crosses a hard-risk boundary, show the conflict and obtain a focused confirmation or route the decision through `/man`; do not treat an explicit but unsound fix instruction as sufficient evidence.',
      '- When this is a child investigation, add `--parent <namespace:ULID>`; report and merge the typed outcome through the mancode child commands.',
      '- Change lifecycle only with `mancode workflow update <namespace:ULID> --status <status> --expected-revision <n> --session <id>` and finish with `workflow complete` plus the typed `--outcome`.',
    ],
  },
  manteam: {
    description: 'Coordinate shared governed work through mancode.',
    purpose: 'plan and execute work with explicit team ownership and handoff',
    contextPurpose: 'plan',
    actions: [
      '- Confirm team membership with `mancode team status`; join invited participants before assigning shared work.',
      '- For a new shared task, run `mancode workflow create manteam "<task>" --visibility shared --coordination team --confirm-shared --session <id>`.',
      '- Apply the same decision-readiness gate as `man` before finalizing requirements: validate both clarity and soundness against project facts and team authority. If the goal, scope, acceptance, owner/source of truth, and constraints are clear and consistent, continue without ceremonial questions; if a decision-changing ambiguity, ownership conflict, or hard-risk direction remains, give evidence and a recommendation, ask focused questions, and wait before writing confirmed requirements.',
      '- Persist unresolved team clarification through the same `workflow requirements <namespace:ULID> draft --file <requirements.json>` command as `man`; do not leave ownership questions or partial answers only in chat history.',
      '- Use claims, checkpoints, sync, and handoffs through `mancode team`; never infer ownership from an adapter prompt.',
      '- With git-ref transport, workflow creation plus requirements, plan, review, and verification mutations use an explicit deferred publication boundary: run the workflow command without `--sync`, commit the resulting `.mancode/shared` authority changes together with the matching code head, then run `mancode team sync push <shared:ULID> --expected-task-revision <n>`. Never report cross-clone synchronization before the push returns a receipt. Use `--sync` only for a command whose contract performs an atomic git-ref mutation. If that atomic mutation leaves tracked `.mancode/shared` projection changes for a resumable in-progress or blocked task, commit them, then run the same `team sync push` with the unchanged task revision to rebind the remote code head before another clone resumes the task.',
    ],
  },
  manps: {
    description: 'Inspect project health through mancode.',
    purpose: 'scan project health and review bounded remediation',
    contextPurpose: 'review',
    actions: [
      '- Run `mancode manps [area]` through the same public command entry (`all`, `deps`, `security`, `dead-code`, or `config`).',
      '- Add `--remediate` only when the operator explicitly requests an interactive remediation review.',
    ],
  },
  mansolo: {
    description: 'Return to focused solo execution through mancode.',
    purpose: 'perform a small focused task or accept an explicit solo handoff',
    contextPurpose: 'implement',
    actions: [
      '- Do not create or persist a legacy solo mode. Ordinary focused work needs no TaskRef; if the operator expects a governed task, use its bound TaskRef or report that none is bound.',
      '- Before editing, assess both clarity and soundness using the project facts. If the request is clear, consistent, and low risk, proceed without ceremonial questions. Resolve repository-answerable unknowns yourself; classify the rest as blocking, recommendable, or defaultable. Ask and wait only when a blocking unknown could materially change behavior, scope, acceptance, data, security, compatibility, or ownership.',
      '- A supplied implementation direction is not automatically safe. If it conflicts with repository evidence or involves authentication, payment, sensitive data, deletion, migration, public APIs, untrusted input, concurrency, infrastructure, or another irreversible effect, show the evidence and impact, recommend the safer path, ask for focused confirmation, and wait before editing.',
      '- If resolving the ambiguity requires architecture, semantic owner/source-of-truth, cross-module scope, migration, team coordination, or formal acceptance decisions, recommend `/man`, explain the trigger, and wait for the operator to choose; advice alone never changes mode or authority.',
      '- Detect those governance triggers after the smallest fact check needed to establish them. Stop before exhaustive discovery or proposing a concrete topology, migration layout, or implementation plan that depends on unanswered decisions.',
      '- For a governed-to-solo transition, use `mancode workflow handoff <namespace:ULID> --to solo --expected-revision <n> --session <id>`.',
    ],
  },
};

async function renderV3AdapterCandidate(
  root: string,
  platform: PlatformName,
): Promise<string> {
  switch (platform) {
    case 'claude-code': {
      const existing = await readAdapterTarget(root, 'claude-skill');
      return replaceManagedV3BlockText(
        existing ?? '',
        CONTINUITY_CLAUDE_START_MARKER,
        CONTINUITY_CLAUDE_END_MARKER,
        renderV3Bootstrap(platform),
      );
    }
    case 'cursor': {
      const existing = await readAdapterTarget(root, 'cursor-rule');
      return managedFilePlan(
        'cursor-rule',
        existing,
        renderCursorRule(renderV3Bootstrap(platform)),
      ).targetContent;
    }
    case 'codex': {
      const existing = (await readAdapterTarget(root, 'agents')) ?? '';
      return replaceManagedV3BlockText(
        removeLegacyV3Block(
          removeLegacyAgentsBlocks(existing),
          LEGACY_V3_CODEX_MARKERS,
        ),
        V3_CODEX_START_MARKER,
        V3_CODEX_END_MARKER,
        renderV3Bootstrap(platform),
      );
    }
    case 'copilot': {
      const existing =
        (await readAdapterTarget(root, 'copilot-instructions')) ?? '';
      return replaceManagedV3BlockText(
        removeLegacyV3Block(
          removeManagedBlock(existing),
          LEGACY_V3_COPILOT_MARKERS,
        ),
        V3_COPILOT_START_MARKER,
        V3_COPILOT_END_MARKER,
        renderV3Bootstrap(platform),
      );
    }
    case 'zcode': {
      const existing = (await readAdapterTarget(root, 'agents')) ?? '';
      return replaceManagedV3BlockText(
        removeLegacyV3Block(
          removeLegacyAgentsBlocks(existing),
          LEGACY_V3_ZCODE_MARKERS,
        ),
        V3_ZCODE_START_MARKER,
        V3_ZCODE_END_MARKER,
        renderV3Bootstrap(platform),
      );
    }
  }
}

function renderCursorRule(content: string): string {
  return [
    '---',
    'description: "Stable bootstrap for mancode context and workflow commands."',
    'alwaysApply: true',
    'globs: "**/*"',
    '---',
    '',
    content,
    '',
  ].join('\n');
}

function managedTargetSpecs(
  root: string,
  platform: PlatformName,
): V3AdapterManagedTargetSpec[] {
  const primary = primaryManagedTargetSpec(platform);
  const modes = V3_MODE_NAMES.map((mode) => {
    const fileTarget = modeEntryFileTarget(platform, mode);
    return {
      identity: fileTarget,
      target: relativeAdapterPath(root, v3ModeEntryPath(root, platform, mode)),
      fileTarget,
      expectedManagedContent: renderV3ModeEntry(mode, platform),
      blockMarkers: null,
    } satisfies V3AdapterManagedTargetSpec;
  });
  return [primary, ...modes];
}

function normalizeUpgradePlatforms(
  platforms: readonly PlatformName[],
): PlatformName[] {
  if (!Array.isArray(platforms) || platforms.length === 0) {
    throw new Error('MANCODE_ADAPTER_UPGRADE_PLATFORM_REQUIRED');
  }
  const selected = new Set<PlatformName>();
  for (const platform of platforms) {
    if (!V3_ADAPTER_PLATFORMS.includes(platform)) {
      throw new Error('MANCODE_ADAPTER_UPGRADE_PLATFORM_INVALID');
    }
    selected.add(platform);
  }
  return V3_ADAPTER_PLATFORMS.filter((platform) => selected.has(platform));
}

function primaryFileTarget(platform: PlatformName): V3AdapterFileTarget {
  switch (platform) {
    case 'claude-code':
      return 'claude-skill';
    case 'cursor':
      return 'cursor-rule';
    case 'codex':
    case 'zcode':
      return 'agents';
    case 'copilot':
      return 'copilot-instructions';
  }
}

function planPlatformBootstrapUpgrade(
  desired: Map<V3AdapterFileTarget, string | null>,
  platform: PlatformName,
): void {
  const target = primaryFileTarget(platform);
  const current = desired.get(target) ?? null;
  switch (platform) {
    case 'claude-code':
      desired.set(
        target,
        replaceManagedV3BlockText(
          current ?? '',
          CONTINUITY_CLAUDE_START_MARKER,
          CONTINUITY_CLAUDE_END_MARKER,
          renderV3Bootstrap(platform),
        ),
      );
      return;
    case 'cursor':
      desired.set(
        target,
        managedFilePlan(
          target,
          current,
          renderCursorRule(renderV3Bootstrap(platform)),
        ).targetContent,
      );
      return;
    case 'codex':
      desired.set(
        target,
        replaceManagedV3BlockText(
          removeLegacyV3Block(
            removeLegacyAgentsBlocks(current ?? ''),
            LEGACY_V3_CODEX_MARKERS,
          ),
          V3_CODEX_START_MARKER,
          V3_CODEX_END_MARKER,
          renderV3Bootstrap(platform),
        ),
      );
      return;
    case 'zcode':
      desired.set(
        target,
        replaceManagedV3BlockText(
          removeLegacyV3Block(
            removeLegacyAgentsBlocks(current ?? ''),
            LEGACY_V3_ZCODE_MARKERS,
          ),
          V3_ZCODE_START_MARKER,
          V3_ZCODE_END_MARKER,
          renderV3Bootstrap(platform),
        ),
      );
      return;
    case 'copilot':
      desired.set(
        target,
        replaceManagedV3BlockText(
          removeLegacyV3Block(
            removeManagedBlock(current ?? ''),
            LEGACY_V3_COPILOT_MARKERS,
          ),
          V3_COPILOT_START_MARKER,
          V3_COPILOT_END_MARKER,
          renderV3Bootstrap(platform),
        ),
      );
  }
}

function primaryManagedTargetSpec(
  platform: PlatformName,
): V3AdapterManagedTargetSpec {
  const target = targetFor(platform);
  switch (platform) {
    case 'claude-code':
      return embeddedManagedTargetSpec(
        target,
        'claude-instructions#continuity',
        'claude-skill',
        CONTINUITY_CLAUDE_START_MARKER,
        CONTINUITY_CLAUDE_END_MARKER,
        renderV3Bootstrap(platform),
      );
    case 'cursor':
      return {
        identity: 'cursor-rule',
        target,
        fileTarget: 'cursor-rule',
        expectedManagedContent: renderCursorRule(renderV3Bootstrap(platform)),
        blockMarkers: null,
      };
    case 'codex':
      return embeddedManagedTargetSpec(
        target,
        'agents#codex',
        'agents',
        V3_CODEX_START_MARKER,
        V3_CODEX_END_MARKER,
        renderV3Bootstrap(platform),
      );
    case 'copilot':
      return embeddedManagedTargetSpec(
        target,
        'copilot-instructions#copilot',
        'copilot-instructions',
        V3_COPILOT_START_MARKER,
        V3_COPILOT_END_MARKER,
        renderV3Bootstrap(platform),
      );
    case 'zcode':
      return embeddedManagedTargetSpec(
        target,
        'agents#zcode',
        'agents',
        V3_ZCODE_START_MARKER,
        V3_ZCODE_END_MARKER,
        renderV3Bootstrap(platform),
      );
  }
}

function embeddedManagedTargetSpec(
  target: string,
  identity: string,
  fileTarget: V3AdapterFileTarget,
  startMarker: string,
  endMarker: string,
  content: string,
): V3AdapterManagedTargetSpec {
  return {
    identity,
    target,
    fileTarget,
    expectedManagedContent: [startMarker, content, endMarker].join('\n'),
    blockMarkers: [startMarker, endMarker],
  };
}

function modeEntryFileTarget(
  platform: PlatformName,
  mode: V3ModeName,
): V3ModeEntryFileTarget {
  const family =
    platform === 'claude-code'
      ? 'claude'
      : platform === 'codex' || platform === 'zcode'
        ? 'agents'
        : platform;
  return `${family}-mode-${mode}` as V3ModeEntryFileTarget;
}

async function inspectManagedTarget(
  root: string,
  platform: PlatformName,
  spec: V3AdapterManagedTargetSpec,
): Promise<V3AdapterManagedTargetStatus> {
  const expectedDigest = adapterManagedContentDigest(
    spec.identity,
    spec.expectedManagedContent,
  );
  const repair = [
    `Preview with \`mancode adapter upgrade --platform ${platform} --dry-run\`.`,
    `Confirm that exact preview with \`mancode adapter upgrade --platform ${platform} --confirm --operation-id <operationId> --session <id>\`.`,
  ].join(' ');
  try {
    const bytes = await readAdapterBytesIfExists(
      root,
      v3AdapterTargetPath(root, spec.fileTarget),
    );
    if (bytes === null) {
      return managedTargetStatus(
        spec,
        'missing',
        null,
        expectedDigest,
        repair,
        'Managed target does not exist.',
      );
    }
    const content = new TextDecoder('utf-8', { fatal: true }).decode(bytes);
    let managedContent: string;
    if (spec.blockMarkers === null) {
      managedContent = content;
    } else {
      try {
        const extracted = extractManagedBlock(
          content,
          spec.blockMarkers[0],
          spec.blockMarkers[1],
        );
        if (extracted === null) {
          return managedTargetStatus(
            spec,
            'missing',
            null,
            expectedDigest,
            repair,
            'Managed block is absent from the target file.',
          );
        }
        managedContent = extracted;
      } catch (error) {
        return managedTargetStatus(
          spec,
          'stale',
          null,
          expectedDigest,
          repair,
          error instanceof Error
            ? error.message
            : 'Managed block is malformed.',
        );
      }
    }
    const actualDigest = adapterManagedContentDigest(
      spec.identity,
      managedContent,
    );
    const status = actualDigest === expectedDigest ? 'ready' : 'stale';
    return managedTargetStatus(
      spec,
      status,
      actualDigest,
      expectedDigest,
      status === 'ready' ? 'none' : repair,
      status === 'ready'
        ? 'Managed content matches the current renderer.'
        : 'Managed content differs from the current renderer.',
    );
  } catch (error) {
    return managedTargetStatus(
      spec,
      'unreadable',
      null,
      expectedDigest,
      `Resolve the filesystem or UTF-8 error, then ${repair}`,
      error instanceof Error ? error.message : 'Managed target is unreadable.',
    );
  }
}

function managedTargetStatus(
  spec: V3AdapterManagedTargetSpec,
  status: V3AdapterContentStatus,
  actualDigest: string | null,
  expectedDigest: string,
  repair: string,
  detail: string,
): V3AdapterManagedTargetStatus {
  return {
    identity: spec.identity,
    target: spec.target,
    status,
    actualDigest,
    expectedDigest,
    rendererVersion: V3_ADAPTER_VERSION,
    repair,
    detail,
  };
}

function aggregateAdapterStatus(
  targets: V3AdapterManagedTargetStatus[],
): V3AdapterContentStatus {
  if (targets.every((target) => target.status === 'ready')) return 'ready';
  if (targets.some((target) => target.status === 'unreadable')) {
    return 'unreadable';
  }
  if (targets.some((target) => target.status === 'stale')) return 'stale';
  return 'missing';
}

function relativeAdapterPath(root: string, target: string): string {
  return path.relative(root, target).split(path.sep).join('/');
}

async function writeManagedFile(
  filePath: string,
  content: string,
): Promise<void> {
  const existing = await readTextIfExists(filePath);
  if (
    existing !== null &&
    !existing.includes(V3_ADAPTER_MANAGED_MARKER) &&
    !existing.includes(LEGACY_V3_ADAPTER_MANAGED_MARKER)
  ) {
    throw new Error('MANCODE_V3_ADAPTER_TARGET_USER_AUTHORED');
  }
  await mkdir(path.dirname(filePath), { recursive: true });
  await atomicWrite(filePath, content);
}

async function writeV3ModeEntry(
  filePath: string,
  content: string,
): Promise<void> {
  const existing = await readTextIfExists(filePath);
  const managed =
    existing === null ||
    existing.includes(V3_MODE_ENTRY_MANAGED_MARKER) ||
    LEGACY_MODE_ENTRY_MANAGED_MARKERS.some((marker) =>
      existing.includes(marker),
    );
  if (!managed) {
    throw new Error('MANCODE_V3_MODE_ENTRY_USER_AUTHORED');
  }
  await mkdir(path.dirname(filePath), { recursive: true });
  await atomicWrite(filePath, content);
}

async function assertV3ModeEntriesWritable(
  root: string,
  platform: PlatformName,
): Promise<void> {
  for (const mode of V3_MODE_NAMES) {
    const existing = await readTextIfExists(
      v3ModeEntryPath(root, platform, mode),
    );
    if (
      existing !== null &&
      !existing.includes(V3_MODE_ENTRY_MANAGED_MARKER) &&
      !LEGACY_MODE_ENTRY_MANAGED_MARKERS.some((marker) =>
        existing.includes(marker),
      )
    ) {
      throw new Error('MANCODE_V3_MODE_ENTRY_USER_AUTHORED');
    }
  }
}

async function removeV3ModeEntry(filePath: string): Promise<void> {
  const existing = await readTextIfExists(filePath);
  if (
    existing?.includes(V3_MODE_ENTRY_MANAGED_MARKER) ||
    LEGACY_MODE_ENTRY_MANAGED_MARKERS.some((marker) =>
      existing?.includes(marker),
    )
  ) {
    await rm(filePath, { force: true });
    await removeDirectoryIfEmpty(path.dirname(filePath));
  }
}

async function removeDirectoryIfEmpty(directory: string): Promise<void> {
  try {
    await rmdir(directory);
  } catch (error) {
    if (
      isNodeError(error) &&
      (error.code === 'ENOENT' ||
        error.code === 'ENOTEMPTY' ||
        error.code === 'EEXIST')
    ) {
      return;
    }
    throw error;
  }
}

async function removeManagedFile(filePath: string): Promise<void> {
  const existing = await readTextIfExists(filePath);
  if (existing?.includes(V3_ADAPTER_MANAGED_MARKER)) {
    await rm(filePath, { force: true });
  }
}

async function removeRetiredBootstrapFiles(
  root: string,
  platform: PlatformName,
): Promise<void> {
  if (platform !== 'claude-code' && platform !== 'cursor') return;
  for (const retired of retiredBootstrapSpecs(root, platform)) {
    await assertAdapterPathSafe(root, retired.filePath);
    const existing = await readTextIfExists(retired.filePath);
    if (!retired.managedMarkers.some((marker) => existing?.includes(marker))) {
      continue;
    }
    await rm(retired.filePath, { force: true });
    await removeDirectoryIfEmpty(path.dirname(retired.filePath));
  }
}

async function replaceManagedV3Block(
  filePath: string,
  startMarker: string,
  endMarker: string,
  content: string,
  legacyMarkers?: readonly (readonly [string, string])[],
): Promise<void> {
  const current = (await readTextIfExists(filePath)) ?? '';
  const existing = (legacyMarkers ?? []).reduce(
    (contentWithoutLegacy, [legacyStart, legacyEnd]) =>
      removeManagedBlock(contentWithoutLegacy, legacyStart, legacyEnd),
    current,
  );
  const block = [startMarker, content, endMarker].join('\n');
  await mkdir(path.dirname(filePath), { recursive: true });
  await atomicWrite(
    filePath,
    replaceManagedBlock(existing, block, startMarker, endMarker),
  );
}

function removeLegacyAgentsBlocks(existing: string): string {
  return removeManagedBlock(
    removeManagedBlock(
      existing,
      LEGACY_CODEX_START_MARKER,
      LEGACY_CODEX_END_MARKER,
    ),
    LEGACY_ZCODE_START_MARKER,
    LEGACY_ZCODE_END_MARKER,
  );
}

function removeLegacyV3Block(
  existing: string,
  markers: readonly [string, string],
): string {
  return removeManagedBlock(existing, markers[0], markers[1]);
}

function replaceManagedV3BlockText(
  existing: string,
  startMarker: string,
  endMarker: string,
  content: string,
): string {
  return replaceManagedBlock(
    existing,
    [startMarker, content, endMarker].join('\n'),
    startMarker,
    endMarker,
  );
}

function managedFilePlan(
  target: V3AdapterFileTarget,
  beforeContent: string | null,
  targetContent: string,
): V3AdapterFilePlan {
  if (
    beforeContent !== null &&
    !beforeContent.includes(V3_ADAPTER_MANAGED_MARKER) &&
    !beforeContent.includes(LEGACY_V3_ADAPTER_MANAGED_MARKER)
  ) {
    throw new Error('MANCODE_V3_ADAPTER_TARGET_USER_AUTHORED');
  }
  return { target, beforeContent, targetContent };
}

function managedModeEntryPlan(
  target: V3ModeEntryFileTarget,
  beforeContent: string | null,
  targetContent: string,
): V3AdapterFilePlan {
  if (
    beforeContent !== null &&
    !beforeContent.includes(V3_MODE_ENTRY_MANAGED_MARKER) &&
    !LEGACY_MODE_ENTRY_MANAGED_MARKERS.some((marker) =>
      beforeContent.includes(marker),
    )
  ) {
    throw new Error('MANCODE_V3_MODE_ENTRY_USER_AUTHORED');
  }
  return { target, beforeContent, targetContent };
}

function planLegacyAdapterRetirement(
  existing: ReadonlyMap<V3AdapterFileTarget, string | null>,
): V3AdapterFilePlan[] {
  const plans: V3AdapterFilePlan[] = [];
  const settings = existing.get('claude-settings') ?? null;
  if (settings !== null) {
    const cleaned = removeLegacyClaudeSettings(settings);
    if (cleaned !== settings) {
      plans.push({
        target: 'claude-settings',
        beforeContent: settings,
        targetContent: cleaned,
      });
    }
  }

  const legacySolo = existing.get('claude-legacy-solo') ?? null;
  if (
    legacySolo?.includes(
      '<!-- Managed by mancode:claude-skill. Do not edit this marker. -->',
    )
  ) {
    plans.push({
      target: 'claude-legacy-solo',
      beforeContent: legacySolo,
      targetContent: renderRetiredClaudeSoloEntry(),
    });
  }

  for (const target of V3_LEGACY_ADAPTER_FILE_TARGETS) {
    if (!target.startsWith('cursor-legacy-')) continue;
    const beforeContent = existing.get(target) ?? null;
    if (
      beforeContent?.includes(
        '<!-- Managed by mancode:cursor-rule. Do not edit this marker. -->',
      )
    ) {
      plans.push({
        target,
        beforeContent,
        targetContent: renderRetiredCursorRule(target),
      });
    }
  }
  for (const target of V3_LEGACY_ADAPTER_FILE_TARGETS) {
    const alias = parseLegacyModeAliasTarget(target);
    if (alias === null) continue;
    const beforeContent = existing.get(target) ?? null;
    if (
      beforeContent !== null &&
      isGeneratedLegacyModeAlias(beforeContent, alias.alias)
    ) {
      plans.push({
        target,
        beforeContent,
        targetContent: renderRetiredModeAlias(target),
      });
    }
  }
  return plans;
}

async function retireLegacyPlatformFiles(
  root: string,
  platform: PlatformName,
): Promise<void> {
  const targets = legacyAdapterTargetsForPlatform(platform, true);
  if (targets.length === 0) return;
  const existing = new Map<V3AdapterFileTarget, string | null>();
  for (const target of targets) {
    existing.set(target, await readAdapterTarget(root, target));
  }
  for (const plan of planLegacyAdapterRetirement(existing)) {
    await applyV3AdapterFilePlan(root, plan);
  }
}

async function removeRetiredLegacyPlatformFiles(
  root: string,
  platform: PlatformName,
): Promise<void> {
  const targets = legacyAdapterTargetsForPlatform(platform, false);
  for (const target of targets) {
    const filePath = v3AdapterTargetPath(root, target);
    const content = await readTextIfExists(filePath);
    const retiredModeEntry =
      target === 'claude-legacy-solo' ||
      parseLegacyModeAliasTarget(target) !== null;
    const retired = content?.includes(
      retiredModeEntry
        ? V3_MODE_ENTRY_MANAGED_MARKER
        : V3_ADAPTER_MANAGED_MARKER,
    );
    if (retired) {
      await rm(filePath, { force: true });
      if (
        target === 'claude-legacy-solo' ||
        target.startsWith('claude-alias-') ||
        target.startsWith('agents-alias-')
      ) {
        await removeDirectoryIfEmpty(path.dirname(filePath));
      }
    }
  }
}

function legacyAdapterTargetsForPlatform(
  platform: PlatformName,
  includeSettings: boolean,
): V3LegacyAdapterFileTarget[] {
  if (platform === 'claude-code') {
    return [
      ...(includeSettings ? (['claude-settings'] as const) : []),
      'claude-legacy-solo',
      ...V3_LEGACY_ADAPTER_FILE_TARGETS.filter((target) =>
        target.startsWith('claude-alias-'),
      ),
    ];
  }
  if (platform === 'cursor') {
    return V3_LEGACY_ADAPTER_FILE_TARGETS.filter((target) =>
      /^(cursor-legacy|cursor-alias)-/u.test(target),
    );
  }
  if (platform === 'codex' || platform === 'zcode') {
    return V3_LEGACY_ADAPTER_FILE_TARGETS.filter((target) =>
      target.startsWith('agents-alias-'),
    );
  }
  return V3_LEGACY_ADAPTER_FILE_TARGETS.filter((target) =>
    target.startsWith('copilot-alias-'),
  );
}

function removeLegacyClaudeSettings(content: string): string {
  const hasKnownLegacyReference = LEGACY_CLAUDE_SETTINGS_RAW_HINTS.some(
    (value) => content.includes(value),
  );
  if (!hasKnownLegacyReference) return content;
  let parsed: unknown;
  try {
    parsed = JSON.parse(content);
  } catch {
    throw new Error('MANCODE_V3_CLAUDE_SETTINGS_INVALID');
  }
  if (!isRecord(parsed)) {
    throw new Error('MANCODE_V3_CLAUDE_SETTINGS_INVALID');
  }
  const hasGeneratedHook = containsGeneratedClaudeHookValue(parsed.hooks);
  const hasGeneratedSkill =
    isRecord(parsed.skills) &&
    Object.values(parsed.skills).some(
      (value) =>
        typeof value === 'string' && LEGACY_CLAUDE_SKILL_PATHS.has(value),
    );
  if (!hasGeneratedHook && !hasGeneratedSkill) return content;
  const settings: Record<string, unknown> = { ...parsed };
  if ('hooks' in settings) {
    const hooks = removeGeneratedClaudeHookValue(settings.hooks);
    if (hooks === undefined) settings.hooks = undefined;
    else settings.hooks = hooks;
  }
  if (isRecord(settings.skills)) {
    const skills = Object.fromEntries(
      Object.entries(settings.skills).filter(
        ([, value]) =>
          typeof value !== 'string' || !LEGACY_CLAUDE_SKILL_PATHS.has(value),
      ),
    );
    if (Object.keys(skills).length === 0) settings.skills = undefined;
    else settings.skills = skills;
  }
  return `${JSON.stringify(settings, null, 2)}\n`;
}

function containsGeneratedClaudeHookValue(value: unknown): boolean {
  if (Array.isArray(value)) {
    return value.some(containsGeneratedClaudeHookValue);
  }
  if (!isRecord(value)) return false;
  if (
    typeof value.command === 'string' &&
    isGeneratedClaudeHookCommand(value.command)
  ) {
    return true;
  }
  return Object.values(value).some(containsGeneratedClaudeHookValue);
}

function removeGeneratedClaudeHookValue(value: unknown): unknown | undefined {
  if (Array.isArray(value)) {
    const cleaned = value
      .map(removeGeneratedClaudeHookValue)
      .filter((entry) => entry !== undefined);
    return cleaned.length > 0 ? cleaned : undefined;
  }
  if (!isRecord(value)) return value;
  if (
    typeof value.command === 'string' &&
    isGeneratedClaudeHookCommand(value.command)
  ) {
    return undefined;
  }
  if (Array.isArray(value.hooks)) {
    const hooks = value.hooks
      .map(removeGeneratedClaudeHookValue)
      .filter((entry) => entry !== undefined);
    return hooks.length > 0 ? { ...value, hooks } : undefined;
  }
  const cleaned = Object.entries(value).flatMap(([key, entry]) => {
    const next = removeGeneratedClaudeHookValue(entry);
    return next === undefined ? [] : [[key, next] as const];
  });
  return cleaned.length > 0 ? Object.fromEntries(cleaned) : undefined;
}

function isGeneratedClaudeHookCommand(command: string): boolean {
  return GENERATED_CLAUDE_HOOK_COMMANDS.has(command.trim());
}

function renderRetiredClaudeSoloEntry(): string {
  return [
    '---',
    'name: solo',
    'description: "Compatibility alias for the mancode mansolo entry."',
    'user-invocable: false',
    '---',
    '',
    V3_MODE_ENTRY_MANAGED_MARKER,
    '',
    '# mancode mode compatibility alias',
    '',
    'Use the `mansolo` mode entry. Resolve mancode status, identity, session, TaskRef, and Context Pack there; do not use legacy mode persistence.',
    '',
  ].join('\n');
}

function renderRetiredCursorRule(target: V3LegacyAdapterFileTarget): string {
  const legacyName = target.replace('cursor-legacy-', '');
  const mode =
    legacyName === 'solo'
      ? 'mansolo'
      : legacyName === 'mamba'
        ? 'manba'
        : legacyName === 'man8'
          ? 'man'
          : legacyName;
  const guidance =
    mode === 'context' || mode === 'practice'
      ? 'Run `mancode status --brief --json`, then use the matching mancode mode command.'
      : `Use the \`/${mode}\` mancode mode command.`;
  return [
    '---',
    'description: "Retired legacy mancode rule; current mancode mode entries are authoritative."',
    'alwaysApply: false',
    'globs: "__mancode_v3_retired_rule__"',
    '---',
    '',
    V3_ADAPTER_MANAGED_MARKER,
    '',
    '# mancode compatibility redirect',
    '',
    guidance,
    'Do not use legacy mode persistence or legacy workflow paths.',
    '',
  ].join('\n');
}

function renderRetiredModeAlias(target: V3AdapterFileTarget): string {
  const parsed = parseLegacyModeAliasTarget(target);
  if (parsed === null) {
    throw new Error('MANCODE_V3_ADAPTER_TARGET_INVALID');
  }
  const publicMode = parsed.alias === 'mamba' ? 'manba' : 'man';
  const frontmatter = [
    '---',
    ...(parsed.family === 'claude' || parsed.family === 'agents'
      ? [`name: ${parsed.alias}`]
      : []),
    ...(parsed.family === 'copilot' ? ["agent: 'agent'"] : []),
    ...(parsed.family === 'claude' ? ['user-invocable: false'] : []),
    `description: ${JSON.stringify(`Compatibility alias for the mancode ${publicMode} entry.`)}`,
    '---',
  ];
  return [
    ...frontmatter,
    '',
    V3_MODE_ENTRY_MANAGED_MARKER,
    '',
    '# mancode mode compatibility alias',
    '',
    `The legacy name \`${parsed.alias}\` maps to the public mancode mode \`${publicMode}\`. Use that original mancode mode entry instead.`,
    '',
    'Resolve status, identity, session, TaskRef, and Context Pack through mancode there. Do not use legacy mode persistence or the legacy workflow protocol.',
    '',
  ].join('\n');
}

function isGeneratedLegacyModeAlias(
  content: string,
  alias: LegacyModeAlias,
): boolean {
  if (
    content.includes(V3_MODE_ENTRY_MANAGED_MARKER) ||
    LEGACY_MODE_ENTRY_MANAGED_MARKERS.some((marker) => content.includes(marker))
  ) {
    return true;
  }
  if (alias !== 'man8') return false;
  return (
    content.includes('# mancode · /man8 (4 AM Warmup)') ||
    (content.includes('# mancode man8 — Investigate and Plan') &&
      content.includes('## Mode Persistence'))
  );
}

function legacyAdapterRelativePath(target: V3AdapterFileTarget): string | null {
  if (target === 'claude-settings')
    return path.join('.claude', 'settings.json');
  if (target === 'claude-legacy-solo') {
    return path.join('.claude', 'skills', 'solo', 'SKILL.md');
  }
  if (target.startsWith('cursor-legacy-')) {
    const name = target.slice('cursor-legacy-'.length);
    return path.join('.cursor', 'rules', `mancode-${name}.mdc`);
  }
  const alias = parseLegacyModeAliasTarget(target);
  if (alias === null) return null;
  switch (alias.family) {
    case 'claude':
      return path.join('.claude', 'skills', alias.alias, 'SKILL.md');
    case 'agents':
      return path.join('.agents', 'skills', alias.alias, 'SKILL.md');
    case 'cursor':
      return path.join('.cursor', 'commands', `${alias.alias}.md`);
    case 'copilot':
      return path.join('.github', 'prompts', `${alias.alias}.prompt.md`);
  }
}

function parseLegacyModeAliasTarget(target: V3AdapterFileTarget): {
  family: 'claude' | 'agents' | 'cursor' | 'copilot';
  alias: LegacyModeAlias;
} | null {
  const match = /^(claude|agents|cursor|copilot)-alias-(mamba|man8)$/u.exec(
    target,
  );
  if (!match) return null;
  return {
    family: match[1] as 'claude' | 'agents' | 'cursor' | 'copilot',
    alias: match[2] as LegacyModeAlias,
  };
}

function renderModeEntryForFileTarget(target: V3ModeEntryFileTarget): string {
  const parsed = parseModeEntryFileTarget(target);
  if (parsed === null) {
    throw new Error('MANCODE_V3_ADAPTER_TARGET_INVALID');
  }
  return renderV3ModeEntry(parsed.mode, parsed.platform);
}

function parseModeEntryFileTarget(
  target: V3AdapterFileTarget,
): { platform: PlatformName; mode: V3ModeName } | null {
  const match =
    /^(claude|agents|cursor|copilot)-mode-(manba|man|manteam|manps|mansolo)$/u.exec(
      target,
    );
  if (!match) return null;
  const family = match[1];
  const mode = match[2] as V3ModeName;
  const platform: PlatformName =
    family === 'claude'
      ? 'claude-code'
      : family === 'agents'
        ? 'codex'
        : family === 'cursor'
          ? 'cursor'
          : 'copilot';
  return { platform, mode };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

async function readAdapterTarget(
  root: string,
  target: V3AdapterFileTarget,
): Promise<string | null> {
  const filePath = v3AdapterTargetPath(root, target);
  await assertAdapterPathSafe(root, filePath);
  try {
    const entry = await lstat(filePath);
    if (!entry.isFile() || entry.isSymbolicLink()) {
      throw new Error('MANCODE_ARTIFACT_PATH_UNSAFE');
    }
  } catch (error) {
    if (isNodeError(error) && error.code === 'ENOENT') return null;
    throw error;
  }
  return readFile(filePath, 'utf8');
}

async function assertPlatformAdapterPathsSafe(
  root: string,
  platform: PlatformName,
): Promise<void> {
  const targets = new Set<string>([
    path.join(root, targetFor(platform)),
    ...V3_MODE_NAMES.map((mode) => v3ModeEntryPath(root, platform, mode)),
    ...legacyAdapterTargetsForPlatform(platform, true).map((target) =>
      v3AdapterTargetPath(root, target),
    ),
  ]);
  if (platform === 'claude-code' || platform === 'cursor') {
    for (const retired of retiredBootstrapSpecs(root, platform)) {
      targets.add(retired.filePath);
    }
  }
  for (const target of targets) {
    await assertAdapterPathSafe(root, target);
  }
}

/** Rejects a symlink or non-directory in any fixed adapter path segment. */
async function assertAdapterPathSafe(
  root: string,
  target: string,
): Promise<void> {
  const relative = path.relative(root, target);
  if (!relative || relative.startsWith('..') || path.isAbsolute(relative)) {
    throw new Error('MANCODE_ARTIFACT_PATH_UNSAFE');
  }
  const rootEntry = await lstat(root);
  if (!rootEntry.isDirectory() || rootEntry.isSymbolicLink()) {
    throw new Error('MANCODE_ARTIFACT_PATH_UNSAFE');
  }
  const segments = relative.split(path.sep);
  let current = root;
  for (let index = 0; index < segments.length; index += 1) {
    current = path.join(current, segments[index] ?? '');
    try {
      const entry = await lstat(current);
      if (
        entry.isSymbolicLink() ||
        (index < segments.length - 1 && !entry.isDirectory())
      ) {
        throw new Error('MANCODE_ARTIFACT_PATH_UNSAFE');
      }
    } catch (error) {
      if (isNodeError(error) && error.code === 'ENOENT') return;
      throw error;
    }
  }
}

async function removeManagedV3Block(
  filePath: string,
  startMarker: string,
  endMarker: string,
): Promise<void> {
  const existing = await readTextIfExists(filePath);
  if (existing === null || !hasManagedBlock(existing, startMarker, endMarker)) {
    return;
  }
  const cleaned = removeManagedBlock(existing, startMarker, endMarker);
  if (cleaned.trim()) {
    await atomicWrite(filePath, `${cleaned.trimEnd()}\n`);
  } else {
    await rm(filePath, { force: true });
  }
}

async function anyManagedBlockPresent(
  filePath: string,
  markerPairs: readonly (readonly [string, string])[],
): Promise<boolean> {
  const content = await readTextIfExists(filePath);
  return (
    content !== null &&
    markerPairs.some(([startMarker, endMarker]) =>
      hasManagedBlock(content, startMarker, endMarker),
    )
  );
}

async function readAdapterBytesIfExists(
  root: string,
  filePath: string,
): Promise<Buffer | null> {
  await assertAdapterPathSafe(root, filePath);
  try {
    const entry = await lstat(filePath);
    if (!entry.isFile() || entry.isSymbolicLink()) {
      throw new Error('MANCODE_ARTIFACT_PATH_UNSAFE');
    }
  } catch (error) {
    if (isNodeError(error) && error.code === 'ENOENT') return null;
    throw error;
  }
  for (let attempt = 1; attempt <= ADAPTER_READ_MAX_ATTEMPTS; attempt += 1) {
    try {
      return await readFile(filePath);
    } catch (error) {
      if (isNodeError(error) && error.code === 'ENOENT') return null;
      if (
        !isRetriableAdapterReadError(error) ||
        attempt === ADAPTER_READ_MAX_ATTEMPTS
      ) {
        throw error;
      }
      await delay(ADAPTER_READ_RETRY_DELAY_MS * attempt);
    }
  }
  throw new Error('MANCODE_V3_ADAPTER_READ_RETRY_EXHAUSTED');
}

async function readTextIfExists(filePath: string): Promise<string | null> {
  for (let attempt = 1; attempt <= ADAPTER_READ_MAX_ATTEMPTS; attempt += 1) {
    try {
      return await readFile(filePath, 'utf8');
    } catch (error) {
      if (isNodeError(error) && error.code === 'ENOENT') return null;
      if (
        !isRetriableAdapterReadError(error) ||
        attempt === ADAPTER_READ_MAX_ATTEMPTS
      ) {
        throw error;
      }
      await delay(ADAPTER_READ_RETRY_DELAY_MS * attempt);
    }
  }
  throw new Error('MANCODE_V3_ADAPTER_READ_RETRY_EXHAUSTED');
}

async function atomicWrite(filePath: string, content: string): Promise<void> {
  const temporary = path.join(
    path.dirname(filePath),
    `.${path.basename(filePath)}.${process.pid}.${Date.now()}.tmp`,
  );
  try {
    await writeFile(temporary, content, { encoding: 'utf8', flag: 'wx' });
    await rename(temporary, filePath);
  } finally {
    await rm(temporary, { force: true }).catch(() => undefined);
  }
}

function targetFor(platform: PlatformName): string {
  switch (platform) {
    case 'claude-code':
      return 'CLAUDE.md';
    case 'cursor':
      return '.cursor/rules/mancode-continuity.mdc';
    case 'codex':
    case 'zcode':
      return 'AGENTS.md';
    case 'copilot':
      return '.github/copilot-instructions.md';
  }
}

function retiredBootstrapPlatformFor(
  target: V3AdapterFileTarget,
): 'claude-code' | 'cursor' | null {
  if (target === 'claude-skill') return 'claude-code';
  if (target === 'cursor-rule') return 'cursor';
  return null;
}

function retiredBootstrapSpecs(
  root: string,
  platform: 'claude-code' | 'cursor',
): Array<{ filePath: string; managedMarkers: readonly string[] }> {
  const managedMarkers = [
    LEGACY_V3_ADAPTER_MANAGED_MARKER,
    V3_ADAPTER_MANAGED_MARKER,
  ] as const;
  if (platform === 'claude-code') {
    return [
      {
        filePath: path.join(
          root,
          '.claude',
          'skills',
          'mancode-v3',
          'SKILL.md',
        ),
        managedMarkers,
      },
      {
        filePath: path.join(
          root,
          '.claude',
          'skills',
          'mancode-continuity',
          'SKILL.md',
        ),
        managedMarkers,
      },
    ];
  }
  return [
    {
      filePath: path.join(root, '.cursor', 'rules', 'mancode-v3.mdc'),
      managedMarkers,
    },
  ];
}

function platformLabelFor(platform: PlatformName): string {
  switch (platform) {
    case 'claude-code':
      return 'Claude Code';
    case 'cursor':
      return 'Cursor';
    case 'codex':
      return 'Codex or ZCode (shared AGENTS.md bootstrap)';
    case 'copilot':
      return 'GitHub Copilot';
    case 'zcode':
      return 'Codex or ZCode (shared AGENTS.md bootstrap)';
  }
}

function capabilitiesFor(_platform: PlatformName): V3AdapterCapabilities {
  return {
    nativeModeEntry: true,
    sessionHook: false,
    promptHook: false,
    sessionIdentity: 'explicit-required',
  };
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return typeof error === 'object' && error !== null && 'code' in error;
}

function isRetriableAdapterReadError(error: unknown): boolean {
  return (
    isNodeError(error) && RETRIABLE_ADAPTER_READ_CODES.has(error.code ?? '')
  );
}

async function delay(milliseconds: number): Promise<void> {
  await new Promise<void>((resolve) => {
    setTimeout(resolve, milliseconds);
  });
}
