import {
  lstat,
  mkdir,
  readFile,
  rename,
  rm,
  rmdir,
  writeFile,
} from 'node:fs/promises';
import path from 'node:path';
import {
  hasManagedBlock,
  removeManagedBlock,
  replaceManagedBlock,
} from './managed-block.js';
import type { PlatformName } from './registry.js';

/**
 * This is the schema of the generated bootstrap, not a product version.  The
 * schema manifest records the expected renderer schema while physical status
 * is derived from the managed files below.
 */
export const V3_ADAPTER_VERSION = '3';

export const V3_ADAPTER_MANAGED_MARKER =
  '<!-- Managed by mancode:v3-adapter. Do not edit this marker. -->';

export const V3_MODE_ENTRY_MANAGED_MARKER =
  '<!-- Managed by mancode:v3-mode-entry. Do not edit this marker. -->';

export const V3_MODE_NAMES = [
  'manba',
  'man',
  'manteam',
  'manps',
  'mansolo',
] as const;

export type V3ModeName = (typeof V3_MODE_NAMES)[number];

const LEGACY_MODE_ENTRY_MANAGED_MARKERS = [
  '<!-- Managed by mancode:claude-skill. Do not edit this marker. -->',
  '<!-- Managed by mancode:codex-skill. Do not edit this file manually. -->',
  '<!-- Managed by mancode:zcode-skill. Do not edit this file manually. -->',
  '<!-- Managed by mancode:mode-file. Do not edit this file manually. -->',
] as const;

const GENERATED_CLAUDE_HOOK_COMMANDS = new Set([
  'node ".mancode/hooks/session-start.mjs"',
  'node ".mancode/hooks/user-prompt-submit.mjs"',
  'bash .mancode/hooks/session-start.sh',
  'bash .mancode/hooks/user-prompt-submit.sh',
]);

const LEGACY_CLAUDE_SKILL_PATHS = new Set([
  '.claude/skills/mancode-solo.md',
  '.claude/skills/mancode-man8.md',
  '.claude/skills/mancode-man.md',
  '.claude/skills/mancode-mansolo.md',
]);

const LEGACY_CLAUDE_SETTINGS_RAW_HINTS = [
  '.mancode/hooks/session-start.',
  '.mancode/hooks/user-prompt-submit.',
  ...LEGACY_CLAUDE_SKILL_PATHS,
] as const;

const V3_CODEX_START_MARKER = '<!-- mancode:v3:codex:start -->';
const V3_CODEX_END_MARKER = '<!-- mancode:v3:codex:end -->';
const V3_ZCODE_START_MARKER = '<!-- mancode:v3:zcode:start -->';
const V3_ZCODE_END_MARKER = '<!-- mancode:v3:zcode:end -->';
const V3_COPILOT_START_MARKER = '<!-- mancode:v3:copilot:start -->';
const V3_COPILOT_END_MARKER = '<!-- mancode:v3:copilot:end -->';
const LEGACY_CODEX_START_MARKER = '<!-- mancode:start -->';
const LEGACY_CODEX_END_MARKER = '<!-- mancode:end -->';
const LEGACY_ZCODE_START_MARKER = '<!-- mancode:zcode:start -->';
const LEGACY_ZCODE_END_MARKER = '<!-- mancode:zcode:end -->';
const RETRIABLE_ADAPTER_READ_CODES = new Set(['EACCES', 'EBUSY', 'EPERM']);
const ADAPTER_READ_MAX_ATTEMPTS = 4;
const ADAPTER_READ_RETRY_DELAY_MS = 25;

export interface V3AdapterCapabilities {
  nativeModeEntry: boolean;
  sessionHook: false;
  promptHook: false;
  sessionIdentity: 'explicit-required';
}

export interface V3PlatformAdapterStatus {
  version: string;
  installed: boolean;
  ready: boolean;
  target: string;
  detail: string;
  capabilities: V3AdapterCapabilities;
}

/**
 * A physical file touched by the V3 bootstrap renderer. Codex and ZCode
 * deliberately share the AGENTS target, so activation journals these files
 * rather than individual platform installs.
 */
export type V3ModeEntryFileTarget =
  | `claude-mode-${V3ModeName}`
  | `agents-mode-${V3ModeName}`
  | `cursor-mode-${V3ModeName}`
  | `copilot-mode-${V3ModeName}`;

export type V3LegacyAdapterFileTarget =
  | 'claude-settings'
  | 'claude-legacy-solo'
  | 'cursor-legacy-context'
  | 'cursor-legacy-practice'
  | 'cursor-legacy-solo'
  | 'cursor-legacy-manba'
  | 'cursor-legacy-man'
  | 'cursor-legacy-manteam'
  | 'cursor-legacy-manps'
  | 'cursor-legacy-mamba'
  | 'cursor-legacy-man8'
  | V3LegacyModeAliasTarget;

type V3LegacyModeAliasTarget =
  | `claude-alias-${LegacyModeAlias}`
  | `agents-alias-${LegacyModeAlias}`
  | `cursor-alias-${LegacyModeAlias}`
  | `copilot-alias-${LegacyModeAlias}`;

type LegacyModeAlias = 'mamba' | 'man8';

export type V3AdapterFileTarget =
  | 'claude-skill'
  | 'cursor-rule'
  | 'agents'
  | 'copilot-instructions'
  | V3ModeEntryFileTarget
  | V3LegacyAdapterFileTarget;

export interface V3AdapterFilePlan {
  target: V3AdapterFileTarget;
  beforeContent: string | null;
  targetContent: string;
}

export interface V3StagedAdapter {
  platform: PlatformName;
  /** The corresponding live target, relative to the project root. */
  target: string;
  /** The generated candidate, kept under V3 staging rather than the live target. */
  stagingTarget: string;
  /** Original public mode entries staged beside the bootstrap candidate. */
  modeEntries: Array<{
    mode: V3ModeName;
    target: string;
    stagingTarget: string;
  }>;
}

const V3_MODE_ENTRY_FILE_TARGETS = V3_MODE_NAMES.flatMap((mode) => [
  `claude-mode-${mode}` as const,
  `agents-mode-${mode}` as const,
  `cursor-mode-${mode}` as const,
  `copilot-mode-${mode}` as const,
]);

const V3_LEGACY_ADAPTER_FILE_TARGETS: readonly V3LegacyAdapterFileTarget[] = [
  'claude-settings',
  'claude-legacy-solo',
  'cursor-legacy-context',
  'cursor-legacy-practice',
  'cursor-legacy-solo',
  'cursor-legacy-manba',
  'cursor-legacy-man',
  'cursor-legacy-manteam',
  'cursor-legacy-manps',
  'cursor-legacy-mamba',
  'cursor-legacy-man8',
  ...(['mamba', 'man8'] as const).flatMap((mode) => [
    `claude-alias-${mode}` as const,
    `agents-alias-${mode}` as const,
    `cursor-alias-${mode}` as const,
    `copilot-alias-${mode}` as const,
  ]),
];

export const V3_ADAPTER_FILE_TARGETS: readonly V3AdapterFileTarget[] = [
  'claude-skill',
  'cursor-rule',
  'agents',
  'copilot-instructions',
  ...V3_MODE_ENTRY_FILE_TARGETS,
  ...V3_LEGACY_ADAPTER_FILE_TARGETS,
];

/**
 * Calculates exact file replacements without publishing them. This lets a
 * migration journal bind the combined AGENTS.md result before its first
 * visible write and preserves all user-authored content outside our blocks.
 */
export async function planV3AdapterFiles(
  projectRoot: string,
): Promise<V3AdapterFilePlan[]> {
  const root = path.resolve(projectRoot);
  const existing = new Map<V3AdapterFileTarget, string | null>();
  for (const target of V3_ADAPTER_FILE_TARGETS) {
    existing.set(target, await readAdapterTarget(root, target));
  }
  const agents = removeLegacyAgentsBlocks(existing.get('agents') ?? '');
  const nextAgents = replaceManagedV3BlockText(
    replaceManagedV3BlockText(
      agents,
      V3_CODEX_START_MARKER,
      V3_CODEX_END_MARKER,
      renderV3Bootstrap('codex'),
    ),
    V3_ZCODE_START_MARKER,
    V3_ZCODE_END_MARKER,
    renderV3Bootstrap('zcode'),
  );
  const legacyAdapterPlans = planLegacyAdapterRetirement(existing);
  const plans: V3AdapterFilePlan[] = [
    managedFilePlan(
      'claude-skill',
      existing.get('claude-skill') ?? null,
      renderClaudeSkill(renderV3Bootstrap('claude-code')),
    ),
    managedFilePlan(
      'cursor-rule',
      existing.get('cursor-rule') ?? null,
      renderCursorRule(renderV3Bootstrap('cursor')),
    ),
    {
      target: 'agents',
      beforeContent: existing.get('agents') ?? null,
      targetContent: nextAgents,
    },
    {
      target: 'copilot-instructions',
      beforeContent: existing.get('copilot-instructions') ?? null,
      targetContent: replaceManagedV3BlockText(
        removeManagedBlock(existing.get('copilot-instructions') ?? ''),
        V3_COPILOT_START_MARKER,
        V3_COPILOT_END_MARKER,
        renderV3Bootstrap('copilot'),
      ),
    },
    ...V3_MODE_ENTRY_FILE_TARGETS.map((target) =>
      managedModeEntryPlan(
        target,
        existing.get(target) ?? null,
        renderModeEntryForFileTarget(target),
      ),
    ),
    ...legacyAdapterPlans,
  ];
  return plans;
}

/** Publishes one precomputed fixed-target replacement with atomic rename. */
export async function applyV3AdapterFilePlan(
  projectRoot: string,
  plan: V3AdapterFilePlan,
): Promise<void> {
  const root = path.resolve(projectRoot);
  if (!V3_ADAPTER_FILE_TARGETS.includes(plan.target)) {
    throw new Error('MANCODE_V3_ADAPTER_TARGET_INVALID');
  }
  if (typeof plan.targetContent !== 'string' || !plan.targetContent.trim()) {
    throw new Error('MANCODE_V3_ADAPTER_TARGET_INVALID');
  }
  const target = v3AdapterTargetPath(root, plan.target);
  await assertAdapterPathSafe(root, target);
  await mkdir(path.dirname(target), { recursive: true });
  await atomicWrite(target, plan.targetContent);
}

/**
 * Renders a complete adapter candidate under V3 staging. Shadow integration
 * may inspect this exact replacement without changing a live managed file.
 */
export async function stageV3Adapter(
  projectRoot: string,
  platform: PlatformName,
): Promise<V3StagedAdapter> {
  const root = path.resolve(projectRoot);
  await assertPlatformAdapterPathsSafe(root, platform);
  const target = targetFor(platform);
  const content = await renderV3AdapterCandidate(root, platform);
  const stagingTarget = path.join(
    '.mancode',
    'staging',
    'adapters',
    'v3',
    platform,
    target,
  );
  const destination = path.join(root, stagingTarget);
  await assertAdapterPathSafe(root, destination);
  await mkdir(path.dirname(destination), { recursive: true });
  await atomicWrite(destination, content);
  const modeEntries = [] as V3StagedAdapter['modeEntries'];
  for (const mode of V3_MODE_NAMES) {
    const modeTarget = path.relative(
      root,
      v3ModeEntryPath(root, platform, mode),
    );
    const modeStagingTarget = path.join(
      '.mancode',
      'staging',
      'adapters',
      'v3',
      platform,
      modeTarget,
    );
    const modeDestination = path.join(root, modeStagingTarget);
    await assertAdapterPathSafe(root, modeDestination);
    await mkdir(path.dirname(modeDestination), { recursive: true });
    await atomicWrite(modeDestination, renderV3ModeEntry(mode, platform));
    modeEntries.push({
      mode,
      target: modeTarget,
      stagingTarget: modeStagingTarget,
    });
  }
  return { platform, target, stagingTarget, modeEntries };
}

export function v3AdapterTargetPath(
  projectRoot: string,
  target: V3AdapterFileTarget,
): string {
  const root = path.resolve(projectRoot);
  const modeTarget = parseModeEntryFileTarget(target);
  if (modeTarget !== null) {
    return v3ModeEntryPath(root, modeTarget.platform, modeTarget.mode);
  }
  const legacyTarget = legacyAdapterRelativePath(target);
  if (legacyTarget !== null) return path.join(root, legacyTarget);
  switch (target) {
    case 'claude-skill':
      return path.join(root, '.claude', 'skills', 'mancode-v3', 'SKILL.md');
    case 'cursor-rule':
      return path.join(root, '.cursor', 'rules', 'mancode-v3.mdc');
    case 'agents':
      return path.join(root, 'AGENTS.md');
    case 'copilot-instructions':
      return path.join(root, '.github', 'copilot-instructions.md');
  }
  throw new Error('MANCODE_V3_ADAPTER_TARGET_INVALID');
}

/** Validates every existing segment before a recovery read or removal. */
export async function assertV3AdapterTargetSafe(
  projectRoot: string,
  target: V3AdapterFileTarget,
): Promise<void> {
  const root = path.resolve(projectRoot);
  await assertAdapterPathSafe(root, v3AdapterTargetPath(root, target));
}

/** The original public mode name, rendered at the host's native entry path. */
export function v3ModeEntryPath(
  projectRoot: string,
  platform: PlatformName,
  mode: V3ModeName,
): string {
  const root = path.resolve(projectRoot);
  switch (platform) {
    case 'claude-code':
      return path.join(root, '.claude', 'skills', mode, 'SKILL.md');
    case 'codex':
    case 'zcode':
      return path.join(root, '.agents', 'skills', mode, 'SKILL.md');
    case 'cursor':
      return path.join(root, '.cursor', 'commands', `${mode}.md`);
    case 'copilot':
      return path.join(root, '.github', 'prompts', `${mode}.prompt.md`);
  }
}

/**
 * Writes only stable V3 bootstrap instructions.  In particular, this never
 * creates legacy authority or copies task state into an adapter file.
 */
export async function installV3Adapter(
  projectRoot: string,
  platform: PlatformName,
): Promise<V3PlatformAdapterStatus> {
  const root = path.resolve(projectRoot);
  await assertV3AdapterInstallable(root, platform);
  const content = renderV3Bootstrap(platform);
  switch (platform) {
    case 'claude-code':
      await writeManagedFile(
        path.join(root, '.claude', 'skills', 'mancode-v3', 'SKILL.md'),
        renderClaudeSkill(content),
      );
      break;
    case 'cursor':
      await writeManagedFile(
        path.join(root, '.cursor', 'rules', 'mancode-v3.mdc'),
        renderCursorRule(content),
      );
      break;
    case 'codex':
      await replaceManagedV3Block(
        path.join(root, 'AGENTS.md'),
        V3_CODEX_START_MARKER,
        V3_CODEX_END_MARKER,
        content,
        [
          [LEGACY_CODEX_START_MARKER, LEGACY_CODEX_END_MARKER],
          [LEGACY_ZCODE_START_MARKER, LEGACY_ZCODE_END_MARKER],
        ],
      );
      break;
    case 'copilot':
      await replaceManagedV3Block(
        path.join(root, '.github', 'copilot-instructions.md'),
        V3_COPILOT_START_MARKER,
        V3_COPILOT_END_MARKER,
        content,
        [[LEGACY_CODEX_START_MARKER, LEGACY_CODEX_END_MARKER]],
      );
      break;
    case 'zcode':
      await replaceManagedV3Block(
        path.join(root, 'AGENTS.md'),
        V3_ZCODE_START_MARKER,
        V3_ZCODE_END_MARKER,
        content,
        [
          [LEGACY_CODEX_START_MARKER, LEGACY_CODEX_END_MARKER],
          [LEGACY_ZCODE_START_MARKER, LEGACY_ZCODE_END_MARKER],
        ],
      );
      break;
  }
  await retireLegacyPlatformFiles(root, platform);
  for (const mode of V3_MODE_NAMES) {
    await writeV3ModeEntry(
      v3ModeEntryPath(root, platform, mode),
      renderV3ModeEntry(mode, platform),
    );
  }
  return inspectV3Adapter(root, platform);
}

/**
 * Proves all deterministic adapter writes are safe before initialization or
 * repair publishes its first file. I/O can still fail later, but user-owned
 * targets, malformed managed settings, and unsafe paths cannot leave a known
 * partial install behind.
 */
export async function assertV3AdapterInstallable(
  projectRoot: string,
  platform: PlatformName,
): Promise<void> {
  const root = path.resolve(projectRoot);
  await assertPlatformAdapterPathsSafe(root, platform);
  await assertV3ModeEntriesWritable(root, platform);
  await renderV3AdapterCandidate(root, platform);

  const existing = new Map<V3AdapterFileTarget, string | null>();
  for (const target of legacyAdapterTargetsForPlatform(platform, true)) {
    existing.set(target, await readAdapterTarget(root, target));
  }
  planLegacyAdapterRetirement(existing);
}

/** Physical adapter status intentionally does not infer hook approval. */
export async function inspectV3Adapter(
  projectRoot: string,
  platform: PlatformName,
): Promise<V3PlatformAdapterStatus> {
  const root = path.resolve(projectRoot);
  await assertPlatformAdapterPathsSafe(root, platform);
  const target = targetFor(platform);
  const bootstrapInstalled = await adapterTargetPresent(root, platform);
  const modeEntriesInstalled = (
    await Promise.all(
      V3_MODE_NAMES.map((mode) =>
        v3ModeEntryPresent(v3ModeEntryPath(root, platform, mode)),
      ),
    )
  ).every(Boolean);
  const installed = bootstrapInstalled && modeEntriesInstalled;
  return {
    version: V3_ADAPTER_VERSION,
    installed,
    ready: installed,
    target,
    detail: installed
      ? 'mancode bootstrap and original mode entries are present; session identity is explicit-required.'
      : 'mancode bootstrap or one of its original mode entries is not installed.',
    capabilities: capabilitiesFor(platform),
  };
}

/** Actual on-disk inventory for compatibility gates; never trust manifest echo. */
export async function inspectV3AdapterVersions(
  projectRoot: string,
): Promise<Record<PlatformName, string>> {
  const platforms: PlatformName[] = [
    'claude-code',
    'codex',
    'cursor',
    'copilot',
    'zcode',
  ];
  const entries = await Promise.all(
    platforms.map(async (platform) => {
      const status = await inspectV3Adapter(projectRoot, platform);
      return [platform, status.ready ? status.version : 'missing'] as const;
    }),
  );
  return Object.fromEntries(entries) as Record<PlatformName, string>;
}

/** Removes only the V3 bootstrap owned by this renderer, never V3 authority. */
export async function removeV3Adapter(
  projectRoot: string,
  platform: PlatformName,
): Promise<void> {
  const root = path.resolve(projectRoot);
  await assertPlatformAdapterPathsSafe(root, platform);
  let preserveSharedModeEntries = false;
  switch (platform) {
    case 'claude-code':
      await removeManagedFile(
        path.join(root, '.claude', 'skills', 'mancode-v3', 'SKILL.md'),
      );
      break;
    case 'cursor':
      await removeManagedFile(
        path.join(root, '.cursor', 'rules', 'mancode-v3.mdc'),
      );
      break;
    case 'codex':
      await removeManagedV3Block(
        path.join(root, 'AGENTS.md'),
        V3_CODEX_START_MARKER,
        V3_CODEX_END_MARKER,
      );
      preserveSharedModeEntries = await managedBlockPresent(
        path.join(root, 'AGENTS.md'),
        V3_ZCODE_START_MARKER,
        V3_ZCODE_END_MARKER,
      );
      break;
    case 'copilot':
      await removeManagedV3Block(
        path.join(root, '.github', 'copilot-instructions.md'),
        V3_COPILOT_START_MARKER,
        V3_COPILOT_END_MARKER,
      );
      break;
    case 'zcode':
      await removeManagedV3Block(
        path.join(root, 'AGENTS.md'),
        V3_ZCODE_START_MARKER,
        V3_ZCODE_END_MARKER,
      );
      preserveSharedModeEntries = await managedBlockPresent(
        path.join(root, 'AGENTS.md'),
        V3_CODEX_START_MARKER,
        V3_CODEX_END_MARKER,
      );
      break;
  }
  if (!preserveSharedModeEntries) {
    for (const mode of V3_MODE_NAMES) {
      await removeV3ModeEntry(v3ModeEntryPath(root, platform, mode));
    }
  }
  await removeRetiredLegacyPlatformFiles(root, platform);
}

export function renderV3Bootstrap(platform: PlatformName): string {
  const platformLabel = platformLabelFor(platform);
  const sessionArguments = sessionArgumentsFor(platform);
  const sessionCreationGuidance =
    platform === 'codex' || platform === 'zcode'
      ? 'When status has no `currentSession`, first reuse any explicit session ID already returned in this conversation. Only when neither exists, create one once with `mancode context session new --client codex` in Codex or `mancode context session new --client zcode` in ZCode.'
      : `When status has no \`currentSession\`, first reuse any explicit session ID already returned in this conversation. Only when neither exists, create one once with \`mancode context session new --client ${platform}\`.`;
  const spikePlatform =
    platform === 'codex' || platform === 'zcode'
      ? 'the active Codex or ZCode host'
      : platform;
  const modeEntry = capabilitiesFor(platform).nativeModeEntry
    ? 'Use the platform mode entry only as a shortcut; resolve a Context Pack first.'
    : 'This platform has no native mancode mode entry; use the CLI commands explicitly.';
  return [
    '# mancode bootstrap',
    '',
    V3_ADAPTER_MANAGED_MARKER,
    '',
    `- Platform: ${platformLabel}. This file is a non-authoritative bootstrap.`,
    '- Locate the project root before running mancode commands.',
    '- First run `mancode status --json` from the project root.',
    '- Treat status values such as `authority: "v3"` and `v3_active` as internal machine fields. In operator-facing narration, say `mancode`; never prefix a mode or action with a version label.',
    '- An explicitly invoked original `man`, `manba`, `manteam`, `manps`, or `mansolo` entry supplies its authorized action. Its mode-specific steps override conflicting generic no-task or mutation guidance below.',
    '- In particular, `manps` may run local health scans without an actor, session, or TaskRef. `mansolo` needs them only for an explicit governed handoff.',
    '- If status has no `localIdentity.actorId`, ask for a display name and run `mancode team identity create --name "<display name>"` before creating a session.',
    '- If status reports `currentSession`, reuse it. `currentTask: null` and `MANCODE_TASK_REQUIRED` do not make a session stale.',
    `- ${sessionCreationGuidance} Pass its returned \`sessionId\` and matching client as \`${sessionArguments}\` to every later session command; an \`export\` inside one command tool does not persist to later command tools.`,
    '- Outside an invoked original mode entry, if no current task and no task is explicitly supplied, report "no task bound" and stop. Do not probe workflow subcommands to work around `MANCODE_TASK_REQUIRED`.',
    '- Bootstrap discovery is read-only: before the operator explicitly requests task work, do not run `mancode init`, `mancode migrate`, `mancode workflow`, or inspect mancode installed package/source.',
    `- With an existing or supplied task, read its Context Pack with \`mancode context show --purpose orient ${sessionArguments}\`; for anonymous diagnosis, include an explicit \`--task <namespace:id>\`.`,
    '- After an operator explicitly requests task work, perform mutations only through `mancode workflow`, `mancode team`, and `mancode context` commands with their required revision and session arguments.',
    '- For a mode entry, request the matching Context Pack purpose: `plan`, `implement`, `review`, `verify`, or `handoff`.',
    '- Do not persist task, mode, or session state in this adapter file or any legacy state file.',
    `- ${modeEntry}`,
    `- No approved session or prompt hook is assumed. After a real-host spike is recorded for ${spikePlatform}, a verified host may provide MANCODE_HOST_SESSION_KEY; otherwise mutations require an explicit \`--session\`.`,
  ].join('\n');
}

/**
 * One renderer backs every original mode name. The entry contains navigation
 * only; V3 stores remain the sole authority for sessions, tasks, and workflow
 * revisions.
 */
export function renderV3ModeEntry(
  mode: V3ModeName,
  platform: PlatformName,
): string {
  const definition = V3_MODE_DEFINITIONS[mode];
  const sessionArguments = sessionArgumentsFor(platform);
  const sessionClientGuidance = sessionClientGuidanceFor(platform);
  const sessionCreationGuidance =
    platform === 'codex' || platform === 'zcode'
      ? 'If status has no current session, reuse an explicit session ID already retained in this conversation. Only if neither exists, run `mancode context session new --client codex` in Codex or `mancode context session new --client zcode` in ZCode exactly once, then retain the returned session ID.'
      : `If status has no current session, reuse an explicit session ID already retained in this conversation. Only if neither exists, run \`mancode context session new --client ${platform}\` exactly once and retain the returned session ID.`;
  let authoritySteps: string[];
  if (mode === 'manps') {
    authoritySteps = [
      '1. Run `mancode status --json` from the project root and require active mancode authority.',
      '2. Run the health action below directly. A local scan needs no TaskRef, actor identity, or explicit session.',
      '3. Never read or write legacy mode authority before or after the scan.',
    ];
  } else if (mode === 'mansolo') {
    authoritySteps = [
      '1. Run `mancode status --json` from the project root. Never read or write legacy mode authority.',
      '2. If no governed task is being handed off, continue with focused solo work without creating a persistent mode, actor, session, or TaskRef.',
      `3. For an explicit governed handoff, ensure \`localIdentity.actorId\`, reuse or create the current session, and bind the existing TaskRef. ${sessionCreationGuidance} ${sessionClientGuidance}`,
      `4. For that governed task only, read \`mancode context show --purpose implement ${sessionArguments}\` using the bound or explicit TaskRef.`,
    ];
  } else if (mode === 'man') {
    authoritySteps = [
      '1. Run `mancode status --json` from the project root. Never read or write the legacy authority file.',
      '2. If the request is only a read-only project orientation, introduction, explanation, or summary, inspect the repository and answer directly without creating an actor, session, TaskRef, or workflow. Do not turn an orientation request into a `plan_only` workflow.',
      '3. Only for requested governed task work, if `localIdentity.actorId` is absent, ask for a display name and run `mancode team identity create --name "<display name>"`.',
      `4. Reuse \`currentSession.sessionId\` when present. ${sessionCreationGuidance} ${sessionClientGuidance}`,
      `5. Reuse the current TaskRef. To bind a supplied existing task, run \`mancode context resume <namespace:ULID> ${sessionArguments}\`.`,
      `6. For an existing task, read only the needed Context Pack with \`mancode context show --purpose ${definition.contextPurpose} ${sessionArguments}\`; include \`--task <namespace:ULID>\` when it is not yet bound. For a new task, create it through the mode action first, then read the returned TaskRef's Context Pack.`,
    ];
  } else {
    authoritySteps = [
      '1. Run `mancode status --json` from the project root. Never read or write the legacy authority file.',
      '2. If `localIdentity.actorId` is absent, ask for a display name and run `mancode team identity create --name "<display name>"`.',
      `3. Reuse \`currentSession.sessionId\` when present. ${sessionCreationGuidance} ${sessionClientGuidance}`,
      `4. Reuse the current TaskRef. To bind a supplied existing task, run \`mancode context resume <namespace:ULID> ${sessionArguments}\`.`,
      `5. For an existing task, read only the needed Context Pack with \`mancode context show --purpose ${definition.contextPurpose} ${sessionArguments}\`; include \`--task <namespace:ULID>\` when it is not yet bound. For a new task, create it through the mode action first, then read the returned TaskRef's Context Pack.`,
    ];
  }
  const frontmatter = [
    '---',
    ...(platform === 'claude-code' ||
    platform === 'codex' ||
    platform === 'zcode'
      ? [`name: ${mode}`]
      : []),
    ...(platform === 'copilot' ? ["agent: 'agent'"] : []),
    `description: ${JSON.stringify(definition.description)}`,
    '---',
  ];
  const mutationGuidance =
    mode === 'manps'
      ? 'The local scan and an explicitly requested remediation do not require a TaskRef, workflow revision, actor, or session. Never turn their report files into workflow authority.'
      : mode === 'mansolo'
        ? 'Only an explicit governed handoff mutation requires the bound TaskRef, explicit session, and latest expected revision. Ordinary focused solo work persists no mode state.'
        : 'For every mutation, use the TaskRef, explicit session, matching client, and latest expected revision reported by mancode. Do not emulate the legacy `--step` protocol or persist mode state in an adapter file.';
  const actions = definition.actions.map((action) =>
    action.replaceAll('--session <id>', sessionArguments),
  );
  return [
    ...frontmatter,
    '',
    V3_MODE_ENTRY_MANAGED_MARKER,
    '',
    `# mancode mode: ${mode}`,
    '',
    `Purpose: ${definition.purpose}.`,
    '',
    '## Enter through mancode',
    '',
    ...authoritySteps,
    '',
    '## Mode action',
    '',
    ...actions,
    '',
    'Treat status values such as `authority: "v3"` and `v3_active` as internal machine fields. In operator-facing narration, say `mancode`; never prefix this mode or its actions with a version label.',
    '',
    mutationGuidance,
    '',
  ].join('\n');
}

function sessionArgumentsFor(platform: PlatformName): string {
  const client =
    platform === 'codex' || platform === 'zcode' ? '<active-client>' : platform;
  return `--session <id> --client ${client}`;
}

function sessionClientGuidanceFor(platform: PlatformName): string {
  return platform === 'codex' || platform === 'zcode'
    ? 'Use `--client codex` in Codex or `--client zcode` in ZCode on every command that uses this session.'
    : `Use \`--client ${platform}\` on every command that uses this session.`;
}

const V3_MODE_DEFINITIONS: Record<
  V3ModeName,
  {
    description: string;
    purpose: string;
    contextPurpose:
      | 'orient'
      | 'plan'
      | 'implement'
      | 'review'
      | 'verify'
      | 'handoff';
    actions: string[];
  }
> = {
  man: {
    description: 'Plan and execute governed work through mancode.',
    purpose: 'clarify, plan, implement, verify, and review governed work',
    contextPurpose: 'plan',
    actions: [
      '- For a read-only project orientation, inspect and answer directly; do not create governance records.',
      '- For a new task, run `mancode workflow create man "<task>" --session <id>`.',
      '- Write requirements as semantic JSON with `version: 1`, `goal`, `confirmedScope`, `excludedScope`, `technicalDecisions`, `defaults`, `blockingUnknowns`, all seven `coverage` dimensions, and `acceptanceCriteria`; mancode generates canonical internal IDs and digests.',
      '- Finalize requirements with `mancode workflow requirements <namespace:ULID> finalize --file <requirements.json> --expected-revision <n> --session <id>`.',
      '- Revise or confirm the plan with `mancode workflow plan <namespace:ULID> revise|confirm --expected-revision <n> ... --session <id>`.',
      '- Apply verification and review ledgers with their mancode `apply --file` commands, then use `mancode workflow complete <namespace:ULID> --expected-revision <n> --session <id>`.',
    ],
  },
  manba: {
    description: 'Diagnose and verify a bug through mancode.',
    purpose: 'reproduce, diagnose, fix, and verify a regression',
    contextPurpose: 'implement',
    actions: [
      '- For a new diagnostic task, run `mancode workflow create manba "<task>" --session <id>`.',
      '- When this is a child investigation, add `--parent <namespace:ULID>`; report and merge the typed outcome through the mancode child commands.',
      '- Change lifecycle only with `mancode workflow update <namespace:ULID> --status <status> --expected-revision <n> --session <id>` and finish with `workflow complete` plus the typed `--outcome`.',
    ],
  },
  manteam: {
    description: 'Coordinate shared governed work through mancode.',
    purpose: 'plan and execute work with explicit team ownership and handoff',
    contextPurpose: 'plan',
    actions: [
      '- Confirm team membership with `mancode team status`; join invited participants before assigning shared work.',
      '- For a new shared task, run `mancode workflow create manteam "<task>" --visibility shared --coordination team --confirm-shared --session <id>`.',
      '- Use claims, checkpoints, sync, and handoffs through `mancode team`; never infer ownership from an adapter prompt.',
      '- Use the same mancode requirements, plan, verification, review, and completion commands as `man`, adding `--sync` whenever the active transport requires it.',
    ],
  },
  manps: {
    description: 'Inspect project health through mancode.',
    purpose: 'scan project health and review bounded remediation',
    contextPurpose: 'review',
    actions: [
      '- Run `mancode manps [area]` through the same public command entry (`all`, `deps`, `security`, `dead-code`, or `config`).',
      '- Add `--remediate` only when the operator explicitly requests an interactive remediation review.',
    ],
  },
  mansolo: {
    description: 'Return to focused solo execution through mancode.',
    purpose: 'perform a small focused task or accept an explicit solo handoff',
    contextPurpose: 'implement',
    actions: [
      '- Do not create or persist a legacy solo mode. Ordinary focused work needs no TaskRef; if the operator expects a governed task, use its bound TaskRef or report that none is bound.',
      '- For a governed-to-solo transition, use `mancode workflow handoff <namespace:ULID> --to solo --expected-revision <n> --session <id>`.',
    ],
  },
};

async function renderV3AdapterCandidate(
  root: string,
  platform: PlatformName,
): Promise<string> {
  switch (platform) {
    case 'claude-code': {
      const existing = await readAdapterTarget(root, 'claude-skill');
      return managedFilePlan(
        'claude-skill',
        existing,
        renderClaudeSkill(renderV3Bootstrap(platform)),
      ).targetContent;
    }
    case 'cursor': {
      const existing = await readAdapterTarget(root, 'cursor-rule');
      return managedFilePlan(
        'cursor-rule',
        existing,
        renderCursorRule(renderV3Bootstrap(platform)),
      ).targetContent;
    }
    case 'codex': {
      const existing = (await readAdapterTarget(root, 'agents')) ?? '';
      return replaceManagedV3BlockText(
        removeLegacyAgentsBlocks(existing),
        V3_CODEX_START_MARKER,
        V3_CODEX_END_MARKER,
        renderV3Bootstrap(platform),
      );
    }
    case 'copilot': {
      const existing =
        (await readAdapterTarget(root, 'copilot-instructions')) ?? '';
      return replaceManagedV3BlockText(
        removeManagedBlock(existing),
        V3_COPILOT_START_MARKER,
        V3_COPILOT_END_MARKER,
        renderV3Bootstrap(platform),
      );
    }
    case 'zcode': {
      const existing = (await readAdapterTarget(root, 'agents')) ?? '';
      return replaceManagedV3BlockText(
        removeLegacyAgentsBlocks(existing),
        V3_ZCODE_START_MARKER,
        V3_ZCODE_END_MARKER,
        renderV3Bootstrap(platform),
      );
    }
  }
}

function renderClaudeSkill(content: string): string {
  return [
    '---',
    'name: mancode-v3',
    'description: "Internal bootstrap for the original mancode mode entries."',
    'user-invocable: false',
    '---',
    '',
    content,
    '',
  ].join('\n');
}

function renderCursorRule(content: string): string {
  return [
    '---',
    'description: "Stable bootstrap for mancode context and workflow commands."',
    'alwaysApply: true',
    'globs: "**/*"',
    '---',
    '',
    content,
    '',
  ].join('\n');
}

async function adapterTargetPresent(
  root: string,
  platform: PlatformName,
): Promise<boolean> {
  switch (platform) {
    case 'claude-code':
      return managedFilePresent(
        path.join(root, '.claude', 'skills', 'mancode-v3', 'SKILL.md'),
      );
    case 'cursor':
      return managedFilePresent(
        path.join(root, '.cursor', 'rules', 'mancode-v3.mdc'),
      );
    case 'codex':
      return managedBlockPresent(
        path.join(root, 'AGENTS.md'),
        V3_CODEX_START_MARKER,
        V3_CODEX_END_MARKER,
      );
    case 'copilot':
      return managedBlockPresent(
        path.join(root, '.github', 'copilot-instructions.md'),
        V3_COPILOT_START_MARKER,
        V3_COPILOT_END_MARKER,
      );
    case 'zcode':
      return managedBlockPresent(
        path.join(root, 'AGENTS.md'),
        V3_ZCODE_START_MARKER,
        V3_ZCODE_END_MARKER,
      );
  }
}

async function writeManagedFile(
  filePath: string,
  content: string,
): Promise<void> {
  const existing = await readTextIfExists(filePath);
  if (existing !== null && !existing.includes(V3_ADAPTER_MANAGED_MARKER)) {
    throw new Error('MANCODE_V3_ADAPTER_TARGET_USER_AUTHORED');
  }
  await mkdir(path.dirname(filePath), { recursive: true });
  await atomicWrite(filePath, content);
}

async function writeV3ModeEntry(
  filePath: string,
  content: string,
): Promise<void> {
  const existing = await readTextIfExists(filePath);
  const managed =
    existing === null ||
    existing.includes(V3_MODE_ENTRY_MANAGED_MARKER) ||
    LEGACY_MODE_ENTRY_MANAGED_MARKERS.some((marker) =>
      existing.includes(marker),
    );
  if (!managed) {
    throw new Error('MANCODE_V3_MODE_ENTRY_USER_AUTHORED');
  }
  await mkdir(path.dirname(filePath), { recursive: true });
  await atomicWrite(filePath, content);
}

async function assertV3ModeEntriesWritable(
  root: string,
  platform: PlatformName,
): Promise<void> {
  for (const mode of V3_MODE_NAMES) {
    const existing = await readTextIfExists(
      v3ModeEntryPath(root, platform, mode),
    );
    if (
      existing !== null &&
      !existing.includes(V3_MODE_ENTRY_MANAGED_MARKER) &&
      !LEGACY_MODE_ENTRY_MANAGED_MARKERS.some((marker) =>
        existing.includes(marker),
      )
    ) {
      throw new Error('MANCODE_V3_MODE_ENTRY_USER_AUTHORED');
    }
  }
}

async function removeV3ModeEntry(filePath: string): Promise<void> {
  const existing = await readTextIfExists(filePath);
  if (existing?.includes(V3_MODE_ENTRY_MANAGED_MARKER)) {
    await rm(filePath, { force: true });
    await removeDirectoryIfEmpty(path.dirname(filePath));
  }
}

async function v3ModeEntryPresent(filePath: string): Promise<boolean> {
  const existing = await readTextIfExists(filePath);
  return existing?.includes(V3_MODE_ENTRY_MANAGED_MARKER) ?? false;
}

async function removeDirectoryIfEmpty(directory: string): Promise<void> {
  try {
    await rmdir(directory);
  } catch (error) {
    if (
      isNodeError(error) &&
      (error.code === 'ENOENT' ||
        error.code === 'ENOTEMPTY' ||
        error.code === 'EEXIST')
    ) {
      return;
    }
    throw error;
  }
}

async function removeManagedFile(filePath: string): Promise<void> {
  const existing = await readTextIfExists(filePath);
  if (existing?.includes(V3_ADAPTER_MANAGED_MARKER)) {
    await rm(filePath, { force: true });
  }
}

async function replaceManagedV3Block(
  filePath: string,
  startMarker: string,
  endMarker: string,
  content: string,
  legacyMarkers?: readonly (readonly [string, string])[],
): Promise<void> {
  const current = (await readTextIfExists(filePath)) ?? '';
  const existing = (legacyMarkers ?? []).reduce(
    (contentWithoutLegacy, [legacyStart, legacyEnd]) =>
      removeManagedBlock(contentWithoutLegacy, legacyStart, legacyEnd),
    current,
  );
  const block = [startMarker, content, endMarker].join('\n');
  await mkdir(path.dirname(filePath), { recursive: true });
  await atomicWrite(
    filePath,
    replaceManagedBlock(existing, block, startMarker, endMarker),
  );
}

function removeLegacyAgentsBlocks(existing: string): string {
  return removeManagedBlock(
    removeManagedBlock(
      existing,
      LEGACY_CODEX_START_MARKER,
      LEGACY_CODEX_END_MARKER,
    ),
    LEGACY_ZCODE_START_MARKER,
    LEGACY_ZCODE_END_MARKER,
  );
}

function replaceManagedV3BlockText(
  existing: string,
  startMarker: string,
  endMarker: string,
  content: string,
): string {
  return replaceManagedBlock(
    existing,
    [startMarker, content, endMarker].join('\n'),
    startMarker,
    endMarker,
  );
}

function managedFilePlan(
  target: V3AdapterFileTarget,
  beforeContent: string | null,
  targetContent: string,
): V3AdapterFilePlan {
  if (
    beforeContent !== null &&
    !beforeContent.includes(V3_ADAPTER_MANAGED_MARKER)
  ) {
    throw new Error('MANCODE_V3_ADAPTER_TARGET_USER_AUTHORED');
  }
  return { target, beforeContent, targetContent };
}

function managedModeEntryPlan(
  target: V3ModeEntryFileTarget,
  beforeContent: string | null,
  targetContent: string,
): V3AdapterFilePlan {
  if (
    beforeContent !== null &&
    !beforeContent.includes(V3_MODE_ENTRY_MANAGED_MARKER) &&
    !LEGACY_MODE_ENTRY_MANAGED_MARKERS.some((marker) =>
      beforeContent.includes(marker),
    )
  ) {
    throw new Error('MANCODE_V3_MODE_ENTRY_USER_AUTHORED');
  }
  return { target, beforeContent, targetContent };
}

function planLegacyAdapterRetirement(
  existing: ReadonlyMap<V3AdapterFileTarget, string | null>,
): V3AdapterFilePlan[] {
  const plans: V3AdapterFilePlan[] = [];
  const settings = existing.get('claude-settings') ?? null;
  if (settings !== null) {
    const cleaned = removeLegacyClaudeSettings(settings);
    if (cleaned !== settings) {
      plans.push({
        target: 'claude-settings',
        beforeContent: settings,
        targetContent: cleaned,
      });
    }
  }

  const legacySolo = existing.get('claude-legacy-solo') ?? null;
  if (
    legacySolo?.includes(
      '<!-- Managed by mancode:claude-skill. Do not edit this marker. -->',
    )
  ) {
    plans.push({
      target: 'claude-legacy-solo',
      beforeContent: legacySolo,
      targetContent: renderRetiredClaudeSoloEntry(),
    });
  }

  for (const target of V3_LEGACY_ADAPTER_FILE_TARGETS) {
    if (!target.startsWith('cursor-legacy-')) continue;
    const beforeContent = existing.get(target) ?? null;
    if (
      beforeContent?.includes(
        '<!-- Managed by mancode:cursor-rule. Do not edit this marker. -->',
      )
    ) {
      plans.push({
        target,
        beforeContent,
        targetContent: renderRetiredCursorRule(target),
      });
    }
  }
  for (const target of V3_LEGACY_ADAPTER_FILE_TARGETS) {
    const alias = parseLegacyModeAliasTarget(target);
    if (alias === null) continue;
    const beforeContent = existing.get(target) ?? null;
    if (
      beforeContent !== null &&
      isGeneratedLegacyModeAlias(beforeContent, alias.alias)
    ) {
      plans.push({
        target,
        beforeContent,
        targetContent: renderRetiredModeAlias(target),
      });
    }
  }
  return plans;
}

async function retireLegacyPlatformFiles(
  root: string,
  platform: PlatformName,
): Promise<void> {
  const targets = legacyAdapterTargetsForPlatform(platform, true);
  if (targets.length === 0) return;
  const existing = new Map<V3AdapterFileTarget, string | null>();
  for (const target of targets) {
    existing.set(target, await readAdapterTarget(root, target));
  }
  for (const plan of planLegacyAdapterRetirement(existing)) {
    await applyV3AdapterFilePlan(root, plan);
  }
}

async function removeRetiredLegacyPlatformFiles(
  root: string,
  platform: PlatformName,
): Promise<void> {
  const targets = legacyAdapterTargetsForPlatform(platform, false);
  for (const target of targets) {
    const filePath = v3AdapterTargetPath(root, target);
    const content = await readTextIfExists(filePath);
    const retiredModeEntry =
      target === 'claude-legacy-solo' ||
      parseLegacyModeAliasTarget(target) !== null;
    const retired = content?.includes(
      retiredModeEntry
        ? V3_MODE_ENTRY_MANAGED_MARKER
        : V3_ADAPTER_MANAGED_MARKER,
    );
    if (retired) {
      await rm(filePath, { force: true });
      if (
        target === 'claude-legacy-solo' ||
        target.startsWith('claude-alias-') ||
        target.startsWith('agents-alias-')
      ) {
        await removeDirectoryIfEmpty(path.dirname(filePath));
      }
    }
  }
}

function legacyAdapterTargetsForPlatform(
  platform: PlatformName,
  includeSettings: boolean,
): V3LegacyAdapterFileTarget[] {
  if (platform === 'claude-code') {
    return [
      ...(includeSettings ? (['claude-settings'] as const) : []),
      'claude-legacy-solo',
      ...V3_LEGACY_ADAPTER_FILE_TARGETS.filter((target) =>
        target.startsWith('claude-alias-'),
      ),
    ];
  }
  if (platform === 'cursor') {
    return V3_LEGACY_ADAPTER_FILE_TARGETS.filter((target) =>
      /^(cursor-legacy|cursor-alias)-/u.test(target),
    );
  }
  if (platform === 'codex' || platform === 'zcode') {
    return V3_LEGACY_ADAPTER_FILE_TARGETS.filter((target) =>
      target.startsWith('agents-alias-'),
    );
  }
  return V3_LEGACY_ADAPTER_FILE_TARGETS.filter((target) =>
    target.startsWith('copilot-alias-'),
  );
}

function removeLegacyClaudeSettings(content: string): string {
  const hasKnownLegacyReference = LEGACY_CLAUDE_SETTINGS_RAW_HINTS.some(
    (value) => content.includes(value),
  );
  if (!hasKnownLegacyReference) return content;
  let parsed: unknown;
  try {
    parsed = JSON.parse(content);
  } catch {
    throw new Error('MANCODE_V3_CLAUDE_SETTINGS_INVALID');
  }
  if (!isRecord(parsed)) {
    throw new Error('MANCODE_V3_CLAUDE_SETTINGS_INVALID');
  }
  const hasGeneratedHook = containsGeneratedClaudeHookValue(parsed.hooks);
  const hasGeneratedSkill =
    isRecord(parsed.skills) &&
    Object.values(parsed.skills).some(
      (value) =>
        typeof value === 'string' && LEGACY_CLAUDE_SKILL_PATHS.has(value),
    );
  if (!hasGeneratedHook && !hasGeneratedSkill) return content;
  const settings: Record<string, unknown> = { ...parsed };
  if ('hooks' in settings) {
    const hooks = removeGeneratedClaudeHookValue(settings.hooks);
    if (hooks === undefined) settings.hooks = undefined;
    else settings.hooks = hooks;
  }
  if (isRecord(settings.skills)) {
    const skills = Object.fromEntries(
      Object.entries(settings.skills).filter(
        ([, value]) =>
          typeof value !== 'string' || !LEGACY_CLAUDE_SKILL_PATHS.has(value),
      ),
    );
    if (Object.keys(skills).length === 0) settings.skills = undefined;
    else settings.skills = skills;
  }
  return `${JSON.stringify(settings, null, 2)}\n`;
}

function containsGeneratedClaudeHookValue(value: unknown): boolean {
  if (Array.isArray(value)) {
    return value.some(containsGeneratedClaudeHookValue);
  }
  if (!isRecord(value)) return false;
  if (
    typeof value.command === 'string' &&
    isGeneratedClaudeHookCommand(value.command)
  ) {
    return true;
  }
  return Object.values(value).some(containsGeneratedClaudeHookValue);
}

function removeGeneratedClaudeHookValue(value: unknown): unknown | undefined {
  if (Array.isArray(value)) {
    const cleaned = value
      .map(removeGeneratedClaudeHookValue)
      .filter((entry) => entry !== undefined);
    return cleaned.length > 0 ? cleaned : undefined;
  }
  if (!isRecord(value)) return value;
  if (
    typeof value.command === 'string' &&
    isGeneratedClaudeHookCommand(value.command)
  ) {
    return undefined;
  }
  if (Array.isArray(value.hooks)) {
    const hooks = value.hooks
      .map(removeGeneratedClaudeHookValue)
      .filter((entry) => entry !== undefined);
    return hooks.length > 0 ? { ...value, hooks } : undefined;
  }
  const cleaned = Object.entries(value).flatMap(([key, entry]) => {
    const next = removeGeneratedClaudeHookValue(entry);
    return next === undefined ? [] : [[key, next] as const];
  });
  return cleaned.length > 0 ? Object.fromEntries(cleaned) : undefined;
}

function isGeneratedClaudeHookCommand(command: string): boolean {
  return GENERATED_CLAUDE_HOOK_COMMANDS.has(command.trim());
}

function renderRetiredClaudeSoloEntry(): string {
  return [
    '---',
    'name: solo',
    'description: "Compatibility alias for the mancode mansolo entry."',
    'user-invocable: false',
    '---',
    '',
    V3_MODE_ENTRY_MANAGED_MARKER,
    '',
    '# mancode mode compatibility alias',
    '',
    'Use the `mansolo` mode entry. Resolve mancode status, identity, session, TaskRef, and Context Pack there; do not use legacy mode persistence.',
    '',
  ].join('\n');
}

function renderRetiredCursorRule(target: V3LegacyAdapterFileTarget): string {
  const legacyName = target.replace('cursor-legacy-', '');
  const mode =
    legacyName === 'solo'
      ? 'mansolo'
      : legacyName === 'mamba'
        ? 'manba'
        : legacyName === 'man8'
          ? 'man'
          : legacyName;
  const guidance =
    mode === 'context' || mode === 'practice'
      ? 'Run `mancode status --json`, then use the matching mancode mode command.'
      : `Use the \`/${mode}\` mancode mode command.`;
  return [
    '---',
    'description: "Retired legacy mancode rule; current mancode mode entries are authoritative."',
    'alwaysApply: false',
    'globs: "__mancode_v3_retired_rule__"',
    '---',
    '',
    V3_ADAPTER_MANAGED_MARKER,
    '',
    '# mancode compatibility redirect',
    '',
    guidance,
    'Do not use legacy mode persistence or legacy workflow paths.',
    '',
  ].join('\n');
}

function renderRetiredModeAlias(target: V3AdapterFileTarget): string {
  const parsed = parseLegacyModeAliasTarget(target);
  if (parsed === null) {
    throw new Error('MANCODE_V3_ADAPTER_TARGET_INVALID');
  }
  const publicMode = parsed.alias === 'mamba' ? 'manba' : 'man';
  const frontmatter = [
    '---',
    ...(parsed.family === 'claude' || parsed.family === 'agents'
      ? [`name: ${parsed.alias}`]
      : []),
    ...(parsed.family === 'copilot' ? ["agent: 'agent'"] : []),
    ...(parsed.family === 'claude' ? ['user-invocable: false'] : []),
    `description: ${JSON.stringify(`Compatibility alias for the mancode ${publicMode} entry.`)}`,
    '---',
  ];
  return [
    ...frontmatter,
    '',
    V3_MODE_ENTRY_MANAGED_MARKER,
    '',
    '# mancode mode compatibility alias',
    '',
    `The legacy name \`${parsed.alias}\` maps to the public mancode mode \`${publicMode}\`. Use that original mancode mode entry instead.`,
    '',
    'Resolve status, identity, session, TaskRef, and Context Pack through mancode there. Do not use legacy mode persistence or the legacy workflow protocol.',
    '',
  ].join('\n');
}

function isGeneratedLegacyModeAlias(
  content: string,
  alias: LegacyModeAlias,
): boolean {
  if (
    content.includes(V3_MODE_ENTRY_MANAGED_MARKER) ||
    LEGACY_MODE_ENTRY_MANAGED_MARKERS.some((marker) => content.includes(marker))
  ) {
    return true;
  }
  if (alias !== 'man8') return false;
  return (
    content.includes('# mancode · /man8 (4 AM Warmup)') ||
    (content.includes('# mancode man8 — Investigate and Plan') &&
      content.includes('## Mode Persistence'))
  );
}

function legacyAdapterRelativePath(target: V3AdapterFileTarget): string | null {
  if (target === 'claude-settings')
    return path.join('.claude', 'settings.json');
  if (target === 'claude-legacy-solo') {
    return path.join('.claude', 'skills', 'solo', 'SKILL.md');
  }
  if (target.startsWith('cursor-legacy-')) {
    const name = target.slice('cursor-legacy-'.length);
    return path.join('.cursor', 'rules', `mancode-${name}.mdc`);
  }
  const alias = parseLegacyModeAliasTarget(target);
  if (alias === null) return null;
  switch (alias.family) {
    case 'claude':
      return path.join('.claude', 'skills', alias.alias, 'SKILL.md');
    case 'agents':
      return path.join('.agents', 'skills', alias.alias, 'SKILL.md');
    case 'cursor':
      return path.join('.cursor', 'commands', `${alias.alias}.md`);
    case 'copilot':
      return path.join('.github', 'prompts', `${alias.alias}.prompt.md`);
  }
}

function parseLegacyModeAliasTarget(target: V3AdapterFileTarget): {
  family: 'claude' | 'agents' | 'cursor' | 'copilot';
  alias: LegacyModeAlias;
} | null {
  const match = /^(claude|agents|cursor|copilot)-alias-(mamba|man8)$/u.exec(
    target,
  );
  if (!match) return null;
  return {
    family: match[1] as 'claude' | 'agents' | 'cursor' | 'copilot',
    alias: match[2] as LegacyModeAlias,
  };
}

function renderModeEntryForFileTarget(target: V3ModeEntryFileTarget): string {
  const parsed = parseModeEntryFileTarget(target);
  if (parsed === null) {
    throw new Error('MANCODE_V3_ADAPTER_TARGET_INVALID');
  }
  return renderV3ModeEntry(parsed.mode, parsed.platform);
}

function parseModeEntryFileTarget(
  target: V3AdapterFileTarget,
): { platform: PlatformName; mode: V3ModeName } | null {
  const match =
    /^(claude|agents|cursor|copilot)-mode-(manba|man|manteam|manps|mansolo)$/u.exec(
      target,
    );
  if (!match) return null;
  const family = match[1];
  const mode = match[2] as V3ModeName;
  const platform: PlatformName =
    family === 'claude'
      ? 'claude-code'
      : family === 'agents'
        ? 'codex'
        : family === 'cursor'
          ? 'cursor'
          : 'copilot';
  return { platform, mode };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

async function readAdapterTarget(
  root: string,
  target: V3AdapterFileTarget,
): Promise<string | null> {
  const filePath = v3AdapterTargetPath(root, target);
  await assertAdapterPathSafe(root, filePath);
  try {
    const entry = await lstat(filePath);
    if (!entry.isFile() || entry.isSymbolicLink()) {
      throw new Error('MANCODE_ARTIFACT_PATH_UNSAFE');
    }
  } catch (error) {
    if (isNodeError(error) && error.code === 'ENOENT') return null;
    throw error;
  }
  return readFile(filePath, 'utf8');
}

async function assertPlatformAdapterPathsSafe(
  root: string,
  platform: PlatformName,
): Promise<void> {
  const targets = new Set<string>([
    path.join(root, targetFor(platform)),
    ...V3_MODE_NAMES.map((mode) => v3ModeEntryPath(root, platform, mode)),
    ...legacyAdapterTargetsForPlatform(platform, true).map((target) =>
      v3AdapterTargetPath(root, target),
    ),
  ]);
  for (const target of targets) {
    await assertAdapterPathSafe(root, target);
  }
}

/** Rejects a symlink or non-directory in any fixed adapter path segment. */
async function assertAdapterPathSafe(
  root: string,
  target: string,
): Promise<void> {
  const relative = path.relative(root, target);
  if (!relative || relative.startsWith('..') || path.isAbsolute(relative)) {
    throw new Error('MANCODE_ARTIFACT_PATH_UNSAFE');
  }
  const rootEntry = await lstat(root);
  if (!rootEntry.isDirectory() || rootEntry.isSymbolicLink()) {
    throw new Error('MANCODE_ARTIFACT_PATH_UNSAFE');
  }
  const segments = relative.split(path.sep);
  let current = root;
  for (let index = 0; index < segments.length; index += 1) {
    current = path.join(current, segments[index] ?? '');
    try {
      const entry = await lstat(current);
      if (
        entry.isSymbolicLink() ||
        (index < segments.length - 1 && !entry.isDirectory())
      ) {
        throw new Error('MANCODE_ARTIFACT_PATH_UNSAFE');
      }
    } catch (error) {
      if (isNodeError(error) && error.code === 'ENOENT') return;
      throw error;
    }
  }
}

async function removeManagedV3Block(
  filePath: string,
  startMarker: string,
  endMarker: string,
): Promise<void> {
  const existing = await readTextIfExists(filePath);
  if (existing === null || !hasManagedBlock(existing, startMarker, endMarker)) {
    return;
  }
  const cleaned = removeManagedBlock(existing, startMarker, endMarker);
  if (cleaned.trim()) {
    await atomicWrite(filePath, `${cleaned.trimEnd()}\n`);
  } else {
    await rm(filePath, { force: true });
  }
}

async function managedFilePresent(filePath: string): Promise<boolean> {
  const content = await readTextIfExists(filePath);
  return content?.includes(V3_ADAPTER_MANAGED_MARKER) ?? false;
}

async function managedBlockPresent(
  filePath: string,
  startMarker: string,
  endMarker: string,
): Promise<boolean> {
  const content = await readTextIfExists(filePath);
  return content !== null && hasManagedBlock(content, startMarker, endMarker);
}

async function readTextIfExists(filePath: string): Promise<string | null> {
  for (let attempt = 1; attempt <= ADAPTER_READ_MAX_ATTEMPTS; attempt += 1) {
    try {
      return await readFile(filePath, 'utf8');
    } catch (error) {
      if (isNodeError(error) && error.code === 'ENOENT') return null;
      if (
        !isRetriableAdapterReadError(error) ||
        attempt === ADAPTER_READ_MAX_ATTEMPTS
      ) {
        throw error;
      }
      await delay(ADAPTER_READ_RETRY_DELAY_MS * attempt);
    }
  }
  throw new Error('MANCODE_V3_ADAPTER_READ_RETRY_EXHAUSTED');
}

async function atomicWrite(filePath: string, content: string): Promise<void> {
  const temporary = path.join(
    path.dirname(filePath),
    `.${path.basename(filePath)}.${process.pid}.${Date.now()}.tmp`,
  );
  try {
    await writeFile(temporary, content, { encoding: 'utf8', flag: 'wx' });
    await rename(temporary, filePath);
  } finally {
    await rm(temporary, { force: true }).catch(() => undefined);
  }
}

function targetFor(platform: PlatformName): string {
  switch (platform) {
    case 'claude-code':
      return '.claude/skills/mancode-v3/SKILL.md';
    case 'cursor':
      return '.cursor/rules/mancode-v3.mdc';
    case 'codex':
    case 'zcode':
      return 'AGENTS.md';
    case 'copilot':
      return '.github/copilot-instructions.md';
  }
}

function platformLabelFor(platform: PlatformName): string {
  switch (platform) {
    case 'claude-code':
      return 'Claude Code';
    case 'cursor':
      return 'Cursor';
    case 'codex':
      return 'Codex or ZCode (shared AGENTS.md bootstrap)';
    case 'copilot':
      return 'GitHub Copilot';
    case 'zcode':
      return 'Codex or ZCode (shared AGENTS.md bootstrap)';
  }
}

function capabilitiesFor(_platform: PlatformName): V3AdapterCapabilities {
  return {
    nativeModeEntry: true,
    sessionHook: false,
    promptHook: false,
    sessionIdentity: 'explicit-required',
  };
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return typeof error === 'object' && error !== null && 'code' in error;
}

function isRetriableAdapterReadError(error: unknown): boolean {
  return (
    isNodeError(error) && RETRIABLE_ADAPTER_READ_CODES.has(error.code ?? '')
  );
}

async function delay(milliseconds: number): Promise<void> {
  await new Promise<void>((resolve) => {
    setTimeout(resolve, milliseconds);
  });
}
